/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a145ee6808c
 */

import * as z from "zod";
import { assetsDownloadBackupAsset } from "../../funcs/assetsDownloadBackupAsset.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  asset_id: z.string().describe(
    "The asset ID of the resource. Must be a 32-character hexadecimal string.",
  ),
  version_id: z.string().describe(
    "The version ID of the backup to download. Must be a 32-character hexadecimal string.",
  ),
  api_key: z.string().describe(
    "The API key to use for the request. This is automatically computed by the Cloudinary's SDKs.",
  ).optional(),
  signature: z.string().describe(
    "(Required for signed REST API calls) Used to authenticate the request and based on the parameters you use in the request. When using the Cloudinary SDKs for signed requests, the signature is automatically generated and added to the request. If you manually generate your own signed POST request, you need to manually generate the signature parameter and add it to the request together with the api_key and timestamp parameters.\n",
  ).optional(),
  timestamp: z.int().describe(
    "The timestamp to use for the request in unix time. This is automatically computed by the Cloudinary's SDKs.",
  ).optional(),
};

export const tool$assetsDownloadBackupAsset: ToolDefinition<typeof args> = {
  name: "download-asset-backup",
  description: `Download a backup copy of an asset`,
  annotations: {
    "title": "Download Asset Backup",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await assetsDownloadBackupAsset(
      client,
      args.asset_id,
      args.version_id,
      args.api_key,
      args.signature,
      args.timestamp,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
