/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ed13ba3617a1
 */

import * as z from "zod";
import { assetsListRawFiles } from "../../funcs/assetsListRawFiles.js";
import { Direction$zodSchema } from "../../models/direction.js";
import { FieldsSpec$zodSchema } from "../../models/fieldsspec.js";
import { ListStorageType$zodSchema } from "../../models/liststoragetype.js";
import { formatResult, ToolDefinition } from "../tools.js";
import { ASSET_GALLERY_RESOURCE_URI } from "../asset-gallery-widget.js";

const args = {
  type: ListStorageType$zodSchema.optional().describe(
    `The delivery type. Necessary for prefix filtering.`,
  ),
  prefix: z.string().describe(
    "A public_id prefix. When specified, all assets with that prefix are returned. When using this, the `type` parameter must also be specified.",
  ).optional(),
  public_ids: z.array(z.string()).describe("An array of public IDs to return.")
    .optional(),
  tags: z.boolean().describe(
    "Whether to include the list of tag names assigned to each asset. Default: false",
  ).optional(),
  next_cursor: z.string().describe("Cursor for pagination.").optional(),
  max_results: z.int().describe("Maximum number of results to return (1-500).")
    .optional(),
  direction: Direction$zodSchema.optional().describe(`Sort direction.`),
  start_at: z.iso.datetime({ offset: true }).describe(
    "An ISO-8601 formatted timestamp. When specified, assets created since that timestamp are returned.  Supported only if neither `prefix` nor `public_ids` were passed.",
  ).optional(),
  fields: z.array(FieldsSpec$zodSchema).optional(),
};

export const tool$assetsListRawFiles: ToolDefinition<typeof args> = {
  name: "list-files",
  description: `Get raw assets

Retrieves a list of raw assets. Results can be filtered by various criteria like tags, moderation status, prefix, or specific public IDs.
`,
  scopes: ["librarian"],
  annotations: {
    "title": "List Files",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  _meta: {
    ui: { resourceUri: ASSET_GALLERY_RESOURCE_URI },
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await assetsListRawFiles(
      client,
      args.type,
      args.prefix,
      args.public_ids,
      args.tags,
      args.next_cursor,
      args.max_results,
      args.direction,
      args.start_at,
      args.fields,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
