/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5cdb768c3ac8
 */

import { assetMetadataUpdateAssetsMetadata } from "../../funcs/assetMetadataUpdateAssetsMetadata.js";
import { MetadataUpdateRequest$zodSchema } from "../../models/metadataupdaterequest.js";
import { ResourceType$zodSchema } from "../../models/resourcetype.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  resource_type: ResourceType$zodSchema.describe(
    `The type of resource (image, video, or raw).`,
  ),
  metadata_update_request: MetadataUpdateRequest$zodSchema.describe(
    `The structured metadata values to assign and the assets to assign them to.`,
  ),
};

export const tool$assetMetadataUpdateAssetsMetadata: ToolDefinition<
  typeof args
> = {
  name: "manage-asset-metadata",
  description: `Sets structured metadata values on multiple assets

Assigns structured metadata field values to the given assets, addressing them by public ID.

Values are merged into each asset's existing structured metadata: fields not mentioned
keep their current values, and an empty value clears the field. Every referenced field
must already exist in the product environment. Conditional metadata rules are evaluated
as part of the update.
`,
  scopes: ["librarian"],
  annotations: {
    "title": "Manage Asset Structured Metadata",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await assetMetadataUpdateAssetsMetadata(
      client,
      args.resource_type,
      args.metadata_update_request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
