/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { assetsListVideos } from "../../funcs/assetsListVideos.js";
import { Direction$zodSchema } from "../../models/direction.js";
import { FieldsSpec$zodSchema } from "../../models/fieldsspec.js";
import { ListStorageType$zodSchema } from "../../models/liststoragetype.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  type: ListStorageType$zodSchema.optional(),
  prefix: z.string().describe(
    "A public_id prefix. When specified, all assets with that prefix are returned. When using this, the `type` parameter must also be specified.",
  ).optional(),
  public_ids: z.array(z.string()).describe("An array of public IDs to return.")
    .optional(),
  tags: z.boolean().describe(
    "Whether to include the list of tag names assigned to each asset. Default: false",
  ).optional(),
  next_cursor: z.string().describe("Cursor for pagination.").optional(),
  max_results: z.int().describe("Maximum number of results to return (1-500).")
    .optional(),
  direction: Direction$zodSchema.optional(),
  start_at: z.iso.datetime({ offset: true }).describe(
    "An ISO-8601 formatted timestamp. When specified, assets created since that timestamp are returned.  Supported only if neither `prefix` nor `public_ids` were passed.",
  ).optional(),
  fields: z.array(FieldsSpec$zodSchema).optional(),
};

export const tool$assetsListVideos: ToolDefinition<typeof args> = {
  name: "list-videos",
  description: `Get video assets

Retrieves a list of video assets. Results can be filtered by various criteria like tags, moderation status, prefix, or specific public IDs.
`,
  scopes: ["librarian"],
  annotations: {
    "title": "List Videos",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await assetsListVideos(
      client,
      args.type,
      args.prefix,
      args.public_ids,
      args.tags,
      args.next_cursor,
      args.max_results,
      args.direction,
      args.start_at,
      args.fields,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
