/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { foldersSearchFolders } from "../../funcs/foldersSearchFolders.js";
import { ExpressionUnion$zodSchema } from "../../models/searchfoldersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  expression: ExpressionUnion$zodSchema.optional(),
  sort_by: z.array(z.string()).describe(
    "An array of key-value pairs for sorting. Each value is a key and direction (asc/desc).",
  ).optional(),
  max_results: z.int().default(50).describe(
    "Maximum number of folders to return (max 500, default 50).",
  ),
  next_cursor: z.string().describe(
    "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
  ).optional(),
};

export const tool$foldersSearchFolders: ToolDefinition<typeof args> = {
  name: "search-folders",
  description: `Searches for folders whose attributes match a given expression

Lists the folders that match the specified search expression. Limited to 2000 results. If no parameters are passed, returns the 50 most recently created folders in descending order of creation time.
`,
  scopes: ["librarian"],
  annotations: {
    "title": "Search Folders",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await foldersSearchFolders(
      client,
      args.expression,
      args.sort_by,
      args.max_results,
      args.next_cursor,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
