/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { foldersUpdateFolder } from "../../funcs/foldersUpdateFolder.js";
import { UpdateFolderRequestBody$zodSchema } from "../../models/updatefolderop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  folder: z.string(),
  RequestBody: UpdateFolderRequestBody$zodSchema,
};

export const tool$foldersUpdateFolder: ToolDefinition<typeof args> = {
  name: "move-folder",
  description:
    `Renames or moves an entire folder (along with all assets it contains) to a new location

Renames or moves an entire folder (along with all assets it contains) to a new location within your Cloudinary media library.`,
  scopes: ["librarian"],
  annotations: {
    "title": "Move Folder",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await foldersUpdateFolder(
      client,
      args.folder,
      args.RequestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
