/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c611ad880e5d
 */

import * as z from "zod";
import { initialBackupGetInitialBackup } from "../../funcs/initialBackupGetInitialBackup.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string().describe(
    "The unique identifier of the initial backup operation.",
  ),
};

export const tool$initialBackupGetInitialBackup: ToolDefinition<typeof args> = {
  name: "get-initial-backup",
  description: `Get initial backup

Retrieves the progress and status of a single initial backup operation by its ID.`,
  scopes: ["librarian"],
  annotations: {
    "title": "Get Initial Backup",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await initialBackupGetInitialBackup(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
