/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ce9bbc71d464
 */

import * as z from "zod";
import { initialBackupListInitialBackups } from "../../funcs/initialBackupListInitialBackups.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  max_results: z.int().default(10).describe(
    "The maximum number of results to return. Default is 10.",
  ),
  next_cursor: z.string().describe(
    "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
  ).optional(),
};

export const tool$initialBackupListInitialBackups: ToolDefinition<typeof args> =
  {
    name: "list-initial-backups",
    description: `List initial backups

Lists initial backup operations for the active product environment, ordered from most recent to oldest.`,
    scopes: ["librarian"],
    annotations: {
      "title": "List Initial Backups",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await initialBackupListInitialBackups(
        client,
        args.max_results,
        args.next_cursor,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
