/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3875c29ceafb
 */

import { CloudinaryAssetMgmtCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  DownloadAssetByAssetIdRequest,
  DownloadAssetByAssetIdRequest$zodSchema,
  DownloadAssetByAssetIdResponse,
  DownloadAssetByAssetIdResponse$zodSchema,
} from "../models/downloadassetbyassetidop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export enum DownloadAssetByAssetIdAcceptEnum {
  applicationJsonAccept = "application/json",
  applicationOctetStreamAccept = "application/octet-stream",
  videoWildcardAccept = "video/*",
  imageWildcardAccept = "image/*",
}

/**
 * Download an asset by asset ID
 *
 * @remarks
 * Generates a download link for a specific asset identified by its immutable asset ID,
 * instead of the resource type, delivery type and public ID.
 */
export function assetsDownloadAssetByAssetId(
  client$: CloudinaryAssetMgmtCore,
  asset_id: string,
  format?: string | undefined,
  transformation?: string | undefined,
  attachment?: boolean | undefined,
  target_filename?: string | undefined,
  streaming_attachment?: boolean | undefined,
  expires_at?: number | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    DownloadAssetByAssetIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    asset_id,
    format,
    transformation,
    attachment,
    target_filename,
    streaming_attachment,
    expires_at,
    options,
  ));
}

async function $do(
  client$: CloudinaryAssetMgmtCore,
  asset_id: string,
  format?: string | undefined,
  transformation?: string | undefined,
  attachment?: boolean | undefined,
  target_filename?: string | undefined,
  streaming_attachment?: boolean | undefined,
  expires_at?: number | undefined,
  options?: RequestOptions & {
    acceptHeaderOverride?: DownloadAssetByAssetIdAcceptEnum;
  },
): Promise<
  [
    Result<
      DownloadAssetByAssetIdResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input$: DownloadAssetByAssetIdRequest = {
    asset_id: asset_id,
    format: format,
    transformation: transformation,
    attachment: attachment,
    target_filename: target_filename,
    streaming_attachment: streaming_attachment,
    expires_at: expires_at,
  };

  const parsed$ = safeParse(
    input$,
    (value$) => DownloadAssetByAssetIdRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/v1_1/{cloud_name}/asset/download")(
    pathParams$,
  );
  const query$ = encodeFormQuery({
    "asset_id": payload$.asset_id,
    "attachment": payload$.attachment,
    "expires_at": payload$.expires_at,
    "format": payload$.format,
    "streaming_attachment": payload$.streaming_attachment,
    "target_filename": payload$.target_filename,
    "transformation": payload$.transformation,
  });

  const headers$ = new Headers(compactMap({
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, application/octet-stream;q=0.8, video/*;q=0.5, image/*;q=0",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "downloadAssetByAssetId",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    DownloadAssetByAssetIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.bytes(200, DownloadAssetByAssetIdResponse$zodSchema, {
      key: "twoHundredApplicationOctetStreamBytes",
    }),
    M.bytes(200, DownloadAssetByAssetIdResponse$zodSchema, {
      ctype: "image/*",
      key: "twoHundredImageWildcardBytes",
    }),
    M.bytes(200, DownloadAssetByAssetIdResponse$zodSchema, {
      ctype: "video/*",
      key: "twoHundredVideoWildcardBytes",
    }),
    M.json([400, 401, 403, 404], DownloadAssetByAssetIdResponse$zodSchema, {
      key: "api_error",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
