/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0ef6dc1f305c
 */

import { CloudinaryAssetMgmtCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  DownloadAssetRequest,
  DownloadAssetRequest$zodSchema,
} from "../models/downloadassetop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { ManagedDeliveryType } from "../models/manageddeliverytype.js";
import { ResourceType } from "../models/resourcetype.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export enum DownloadAssetAcceptEnum {
  applicationJsonAccept = "application/json",
  applicationOctetStreamAccept = "application/octet-stream",
  videoWildcardAccept = "video/*",
  imageWildcardAccept = "image/*",
}

/**
 * Generates a download link for a specific asset (image)
 */
export function assetsDownloadAsset(
  client$: CloudinaryAssetMgmtCore,
  resource_type: ResourceType,
  public_id: string,
  format?: string | undefined,
  type?: ManagedDeliveryType | undefined,
  expires_at?: number | undefined,
  attachment?: boolean | undefined,
  target_filename?: string | undefined,
  transformation?: string | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    resource_type,
    public_id,
    format,
    type,
    expires_at,
    attachment,
    target_filename,
    transformation,
    options,
  ));
}

async function $do(
  client$: CloudinaryAssetMgmtCore,
  resource_type: ResourceType,
  public_id: string,
  format?: string | undefined,
  type?: ManagedDeliveryType | undefined,
  expires_at?: number | undefined,
  attachment?: boolean | undefined,
  target_filename?: string | undefined,
  transformation?: string | undefined,
  options?: RequestOptions & { acceptHeaderOverride?: DownloadAssetAcceptEnum },
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input$: DownloadAssetRequest = {
    resource_type: resource_type,
    public_id: public_id,
    format: format,
    type: type,
    expires_at: expires_at,
    attachment: attachment,
    target_filename: target_filename,
    transformation: transformation,
  };

  const parsed$ = safeParse(
    input$,
    (value$) => DownloadAssetRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
    resource_type: encodeSimple("resource_type", payload$.resource_type, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/v1_1/{cloud_name}/{resource_type}/download")(
    pathParams$,
  );
  const query$ = encodeFormQuery({
    "attachment": payload$.attachment,
    "expires_at": payload$.expires_at,
    "format": payload$.format,
    "public_id": payload$.public_id,
    "target_filename": payload$.target_filename,
    "transformation": payload$.transformation,
    "type": payload$.type,
  });

  const headers$ = new Headers(compactMap({
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, application/octet-stream;q=0.8, video/*;q=0.5, image/*;q=0",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "downloadAsset",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
