/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 72ec3bb97e8c
 */

import { CloudinaryAssetMgmtCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  ListResourcesByContainerIdRequest,
  ListResourcesByContainerIdRequest$zodSchema,
  ListResourcesByContainerIdResponse,
  ListResourcesByContainerIdResponse$zodSchema,
} from "../models/listresourcesbycontaineridop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * List the assets in a folder by container ID
 *
 * @remarks
 * Returns the assets contained in the folder identified by the given container ID.
 */
export function assetsListResourcesByContainerId(
  client$: CloudinaryAssetMgmtCore,
  container_id: string,
  max_results?: number | undefined,
  next_cursor?: string | undefined,
  sort_by?: string | undefined,
  fields?: string | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    ListResourcesByContainerIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    container_id,
    max_results,
    next_cursor,
    sort_by,
    fields,
    options,
  ));
}

async function $do(
  client$: CloudinaryAssetMgmtCore,
  container_id: string,
  max_results?: number | undefined,
  next_cursor?: string | undefined,
  sort_by?: string | undefined,
  fields?: string | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      ListResourcesByContainerIdResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input$: ListResourcesByContainerIdRequest = {
    container_id: container_id,
    max_results: max_results,
    next_cursor: next_cursor,
    sort_by: sort_by,
    fields: fields,
  };

  const parsed$ = safeParse(
    input$,
    (value$) => ListResourcesByContainerIdRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
    container_id: encodeSimple("container_id", payload$.container_id, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc(
    "/v1_1/{cloud_name}/resources/by_container_id/{container_id}",
  )(
    pathParams$,
  );
  const query$ = encodeFormQuery({
    "fields": payload$.fields,
    "max_results": payload$.max_results,
    "next_cursor": payload$.next_cursor,
    "sort_by": payload$.sort_by,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "listResourcesByContainerId",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    ListResourcesByContainerIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, ListResourcesByContainerIdResponse$zodSchema, {
      key: "resources_by_container_id_response",
    }),
    M.json([400, 401, 403], ListResourcesByContainerIdResponse$zodSchema, {
      key: "api_error",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
