/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f734afd6b5df
 */

import { CloudinaryAssetMgmtCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  DeleteBackupVersionsOpServerList,
  DeleteBackupVersionsRequestRequest,
  DeleteBackupVersionsRequestRequest$zodSchema,
  DeleteBackupVersionsSecurity,
} from "../models/deletebackupversionsop.js";
import { DeleteBackupVersionsRequest } from "../models/deletebackupversionsrequest.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Delete backed up versions
 *
 * @remarks
 * Deletes specific backed up versions of an asset identified by asset ID.
 * This operation is irreversible and deleted versions cannot be recovered.
 */
export function backupsDeleteBackupVersions(
  client$: CloudinaryAssetMgmtCore,
  security: DeleteBackupVersionsSecurity,
  asset_id: string,
  delete_backup_versions_request: DeleteBackupVersionsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    asset_id,
    delete_backup_versions_request,
    options,
  ));
}

async function $do(
  client$: CloudinaryAssetMgmtCore,
  security: DeleteBackupVersionsSecurity,
  asset_id: string,
  delete_backup_versions_request: DeleteBackupVersionsRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input$: DeleteBackupVersionsRequestRequest = {
    asset_id: asset_id,
    delete_backup_versions_request: delete_backup_versions_request,
  };

  const parsed$ = safeParse(
    input$,
    (value$) => DeleteBackupVersionsRequestRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON("body", payload$.delete_backup_versions_request, {
    explode: true,
  });
  const baseURL$ = options?.serverURL
    || pathToFunc(DeleteBackupVersionsOpServerList[0], {
      charEncoding: "percent",
    })(
      {
        region: "api",
        host: "api.cloudinary.com",
      },
    );

  const pathParams$ = {
    asset_id: encodeSimple("asset_id", payload$.asset_id, {
      explode: false,
      charEncoding: "percent",
    }),
    cloud_name: encodeSimple("cloud_name", client$._options.cloud_name, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/v1_1/{cloud_name}/resources/backup/{asset_id}")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        type: "http:custom",
        value: {
          api_key: security?.cloudinaryAuth?.api_key,
          api_secret: security?.cloudinaryAuth?.api_secret,
        },
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "oauth2",
        value: security?.oauth2,
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: baseURL$ ?? "",
    operationID: "deleteBackupVersions",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "DELETE",
    baseURL: baseURL$,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
