workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CloudinaryAssetMgmt-MCP-OAS:
        inputs:
            - location: https://cloudinary.github.io/api-schemas/asset-management/schema.yml
        overlays:
            - location: https://cloudinary.github.io/api-schemas/overlays/security-scheme-cloud-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/overlays/cloud-name-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/mcp-disabled.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/remove-mcp-description.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/signature-optional-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/asset-management/overlays/remove-multipart-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/asset-management/overlays/create-only-archive-mode-overlay.yml
        registry:
            location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-asset-mgmt-mcp-oas
targets:
    cloudinary-asset-mgmt-mcp:
        target: mcp-typescript
        source: CloudinaryAssetMgmt-MCP-OAS
        publish:
            npm:
                token: $npm_token
