/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b3d5a7a42328
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of access control to apply to the asset.
 */
export const AccessType = {
  Token: "token",
  Anonymous: "anonymous",
} as const;
/**
 * The type of access control to apply to the asset.
 */
export type AccessType = ClosedEnum<typeof AccessType>;

export const AccessType$zodSchema = z.enum([
  "token",
  "anonymous",
]).describe("The type of access control to apply to the asset.");

/**
 * Access control rule that defines when and how the asset can be accessed.
 */
export type AccessControlItem = {
  access_type: AccessType;
  key?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
};

export const AccessControlItem$zodSchema: z.ZodType<AccessControlItem> = z
  .object({
    access_type: AccessType$zodSchema.describe(
      "The type of access control to apply to the asset.",
    ),
    end: z.string().optional().describe(
      "The end date and time when anonymous access expires (ISO 8601 format).",
    ),
    key: z.string().optional().describe(
      "The authentication key identifier for token-based access. Default key is used if not specified or if set to 'default'.",
    ),
    start: z.string().optional().describe(
      "The start date and time when anonymous access becomes available (ISO 8601 format).",
    ),
  }).describe(
    "Access control rule that defines when and how the asset can be accessed.",
  );
