/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 678052f129b0
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The delivery type for archive operations. Managed types plus fetch.
 *
 * @remarks
 */
export const ArchiveDeliveryType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Fetch: "fetch",
} as const;
/**
 * The delivery type for archive operations. Managed types plus fetch.
 *
 * @remarks
 */
export type ArchiveDeliveryType = ClosedEnum<typeof ArchiveDeliveryType>;

export const ArchiveDeliveryType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "fetch",
]).describe(
  "The delivery type for archive operations. Managed types plus fetch.\n",
);
