/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1746f046a48e
 */

import * as z from "zod";

export type BackupVersionFailure = {
  version_id?: string | undefined;
  error?: string | undefined;
};

export const BackupVersionFailure$zodSchema: z.ZodType<BackupVersionFailure> = z
  .object({
    error: z.string().optional().describe(
      "The error message explaining the failure.",
    ),
    version_id: z.string().optional().describe(
      "A 32-character hexadecimal version ID.",
    ),
  });
