/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4293ca98e9a
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { ConcatResponse, ConcatResponse$zodSchema } from "./concatresponse.js";

export type ConcatGlobals = { cloud_name?: string | undefined };

export const ConcatGlobals$zodSchema: z.ZodType<ConcatGlobals> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ConcatResponseResponse = ConcatResponse | ApiError;

export const ConcatResponseResponse$zodSchema: z.ZodType<
  ConcatResponseResponse
> = z.union([
  ConcatResponse$zodSchema,
  ApiError$zodSchema,
]);
