/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4293ca98e9a
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { ConcatResponse, ConcatResponse$zodSchema } from "./concatresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const ConcatOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type ConcatGlobals = { cloud_name?: string | undefined };

export const ConcatGlobals$zodSchema: z.ZodType<ConcatGlobals> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ConcatSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const ConcatSecurity$zodSchema: z.ZodType<ConcatSecurity> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type ConcatResponseResponse = ConcatResponse | ApiError;

export const ConcatResponseResponse$zodSchema: z.ZodType<
  ConcatResponseResponse
> = z.union([
  ConcatResponse$zodSchema,
  ApiError$zodSchema,
]);
