/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 362ede66bfb5
 */

import * as z from "zod";

export type CreateFolderResponse = {
  name: string;
  path: string;
  external_id: string;
  created_at?: string | undefined;
  success?: boolean | undefined;
};

export const CreateFolderResponse$zodSchema: z.ZodType<CreateFolderResponse> = z
  .object({
    created_at: z.iso.datetime({ offset: true }).optional().describe(
      "The timestamp when the folder was created.",
    ),
    external_id: z.string().describe("The unique identifier for the folder."),
    name: z.string().describe("The name of the folder."),
    path: z.string().describe("The full path of the folder."),
    success: z.boolean().optional().describe(
      "Whether the operation was successful.",
    ),
  });
