/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b52cfcc7e7b1
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AssetRelationsResponse,
  AssetRelationsResponse$zodSchema,
} from "./assetrelationsresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  StorageTypeParameter,
  StorageTypeParameter$zodSchema,
} from "./storagetypeparameter.js";

export type CreateAssetRelationsByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const CreateAssetRelationsByPublicIdGlobals$zodSchema: z.ZodType<
  CreateAssetRelationsByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateAssetRelationsByPublicIdRequestBody = {
  assets_to_relate: Array<string>;
};

export const CreateAssetRelationsByPublicIdRequestBody$zodSchema: z.ZodType<
  CreateAssetRelationsByPublicIdRequestBody
> = z.object({
  assets_to_relate: z.array(z.string()).describe(
    "Relates the asset to all the other assets specified in this array of up to 10 assets, specified as resource_type/type/public_id.",
  ),
});

export type CreateAssetRelationsByPublicIdRequest = {
  resource_type: ResourceType;
  type?: StorageTypeParameter | undefined;
  public_id: string;
  RequestBody: CreateAssetRelationsByPublicIdRequestBody;
};

export const CreateAssetRelationsByPublicIdRequest$zodSchema: z.ZodType<
  CreateAssetRelationsByPublicIdRequest
> = z.object({
  RequestBody: z.lazy(() =>
    CreateAssetRelationsByPublicIdRequestBody$zodSchema
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema.describe("The type of resource."),
  type: StorageTypeParameter$zodSchema.default("upload").describe(
    "The delivery type of the asset.",
  ),
});

export type CreateAssetRelationsByPublicIdResponse =
  | ApiError
  | AssetRelationsResponse;

export const CreateAssetRelationsByPublicIdResponse$zodSchema: z.ZodType<
  CreateAssetRelationsByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  AssetRelationsResponse$zodSchema,
]);
