/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8b020d68cf73
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  InitialBackupCreateResponse,
  InitialBackupCreateResponse$zodSchema,
} from "./initialbackupcreateresponse.js";

export const CreateInitialBackupOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type CreateInitialBackupGlobals = { cloud_name?: string | undefined };

export const CreateInitialBackupGlobals$zodSchema: z.ZodType<
  CreateInitialBackupGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateInitialBackupResponse =
  | InitialBackupCreateResponse
  | ApiError;

export const CreateInitialBackupResponse$zodSchema: z.ZodType<
  CreateInitialBackupResponse
> = z.union([
  InitialBackupCreateResponse$zodSchema,
  ApiError$zodSchema,
]);
