/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cda9ad104697
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type CreateFolderGlobals = { cloud_name?: string | undefined };

export const CreateFolderGlobals$zodSchema: z.ZodType<CreateFolderGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type CreateFolderRequest = { folder: string };

export const CreateFolderRequest$zodSchema: z.ZodType<CreateFolderRequest> = z
  .object({
    folder: z.string(),
  });

/**
 * Folder created successfully
 */
export type CreateFolderResponseBody = {
  success?: boolean | undefined;
  path?: string | undefined;
  name?: string | undefined;
};

export const CreateFolderResponseBody$zodSchema: z.ZodType<
  CreateFolderResponseBody
> = z.object({
  name: z.string().optional().describe("The name of the created folder"),
  path: z.string().optional().describe("The path of the created folder"),
  success: z.boolean().optional().describe(
    "Whether the operation was successful",
  ),
}).describe("Folder created successfully");

export type CreateFolderResponse = ApiError | CreateFolderResponseBody;

export const CreateFolderResponse$zodSchema: z.ZodType<CreateFolderResponse> = z
  .union([
    ApiError$zodSchema,
    z.lazy(() => CreateFolderResponseBody$zodSchema),
  ]);
