/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AssetRelationsDeleteResponse,
  AssetRelationsDeleteResponse$zodSchema,
} from "./assetrelationsdeleteresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  StorageTypeParameter,
  StorageTypeParameter$zodSchema,
} from "./storagetypeparameter.js";

export type DeleteAssetRelationsByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteAssetRelationsByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteAssetRelationsByPublicIdRequestBody = {
  assets_to_unrelate: Array<string>;
};

export const DeleteAssetRelationsByPublicIdRequestBody$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  assets_to_unrelate: z.array(z.string()),
});

export type DeleteAssetRelationsByPublicIdRequest = {
  resource_type: ResourceType;
  type?: StorageTypeParameter | undefined;
  public_id: string;
  RequestBody: DeleteAssetRelationsByPublicIdRequestBody;
};

export const DeleteAssetRelationsByPublicIdRequest$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() =>
    DeleteAssetRelationsByPublicIdRequestBody$zodSchema
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema,
  type: StorageTypeParameter$zodSchema.default("upload"),
});

export type DeleteAssetRelationsByPublicIdResponse =
  | ApiError
  | AssetRelationsDeleteResponse;

export const DeleteAssetRelationsByPublicIdResponse$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  AssetRelationsDeleteResponse$zodSchema,
]);
