/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e59aacafd23
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AssetRelationsDeleteResponse,
  AssetRelationsDeleteResponse$zodSchema,
} from "./assetrelationsdeleteresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  StorageTypeParameter,
  StorageTypeParameter$zodSchema,
} from "./storagetypeparameter.js";

export type DeleteAssetRelationsByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteAssetRelationsByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteAssetRelationsByPublicIdRequestBody = {
  assets_to_unrelate: Array<string>;
};

export const DeleteAssetRelationsByPublicIdRequestBody$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequestBody
> = z.object({
  assets_to_unrelate: z.array(z.string()).describe(
    "Unrelates the asset from all the assets specified in this array of assets, specified as resource_type/type/public_id.",
  ),
});

export type DeleteAssetRelationsByPublicIdRequest = {
  resource_type: ResourceType;
  type?: StorageTypeParameter | undefined;
  public_id: string;
  RequestBody: DeleteAssetRelationsByPublicIdRequestBody;
};

export const DeleteAssetRelationsByPublicIdRequest$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequest
> = z.object({
  RequestBody: z.lazy(() =>
    DeleteAssetRelationsByPublicIdRequestBody$zodSchema
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema.describe("The type of resource."),
  type: StorageTypeParameter$zodSchema.default("upload").describe(
    "The delivery type of the asset.",
  ),
});

export type DeleteAssetRelationsByPublicIdResponse =
  | ApiError
  | AssetRelationsDeleteResponse;

export const DeleteAssetRelationsByPublicIdResponse$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  AssetRelationsDeleteResponse$zodSchema,
]);
