/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e59aacafd23
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AssetRelationsDeleteResponse,
  AssetRelationsDeleteResponse$zodSchema,
} from "./assetrelationsdeleteresponse.js";
import { DeliveryType, DeliveryType$zodSchema } from "./deliverytype.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";
import {
  UnrelateAssetsByPublicIdRequest,
  UnrelateAssetsByPublicIdRequest$zodSchema,
} from "./unrelateassetsbypublicidrequest.js";

export const DeleteAssetRelationsByPublicIdOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type DeleteAssetRelationsByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteAssetRelationsByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteAssetRelationsByPublicIdSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const DeleteAssetRelationsByPublicIdSecurity$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type DeleteAssetRelationsByPublicIdRequest = {
  resource_type: ResourceType;
  type?: DeliveryType | undefined;
  public_id: string;
  unrelate_assets_by_public_id_request: UnrelateAssetsByPublicIdRequest;
};

export const DeleteAssetRelationsByPublicIdRequest$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdRequest
> = z.object({
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: DeliveryType$zodSchema.default("upload").describe(
    "The delivery type of the asset.",
  ),
  unrelate_assets_by_public_id_request:
    UnrelateAssetsByPublicIdRequest$zodSchema.describe(
      "The assets to unrelate by public ID.",
    ),
});

export type DeleteAssetRelationsByPublicIdResponse =
  | ApiError
  | AssetRelationsDeleteResponse;

export const DeleteAssetRelationsByPublicIdResponse$zodSchema: z.ZodType<
  DeleteAssetRelationsByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  AssetRelationsDeleteResponse$zodSchema,
]);
