/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 646ef53bcaa5
 */

import * as z from "zod";
import {
  BackupVersionFailure,
  BackupVersionFailure$zodSchema,
} from "./backupversionfailure.js";

export type DeleteBackupVersionsPartialResponse = {
  asset_id: string;
  deleted_version_ids: Array<string>;
  failures?: Array<BackupVersionFailure> | undefined;
};

export const DeleteBackupVersionsPartialResponse$zodSchema: z.ZodType<
  DeleteBackupVersionsPartialResponse
> = z.object({
  asset_id: z.string().describe("A 32-character hexadecimal asset ID."),
  deleted_version_ids: z.array(z.string()).describe(
    "The list of version IDs that were successfully deleted.",
  ),
  failures: z.array(BackupVersionFailure$zodSchema).optional().describe(
    "The list of version IDs that failed to delete with error messages.",
  ),
});
