/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cf9aed5b5a91
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DeleteResourceByPublicIdsRequestUnion,
  DeleteResourceByPublicIdsRequestUnion$zodSchema,
} from "./deleteresourcebypublicidsrequestunion.js";
import { Info, Info$zodSchema } from "./info.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  ResourceUpdateRequest,
  ResourceUpdateRequest$zodSchema,
} from "./resourceupdaterequest.js";

/**
 * All supported delivery types.
 */
export const DeliveryTypeAllEnum = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Asset: "asset",
  Fetch: "fetch",
  Url2png: "url2png",
  Facebook: "facebook",
  Twitter: "twitter",
  TwitterName: "twitter_name",
  Instagram: "instagram",
  InstagramName: "instagram_name",
  Gravatar: "gravatar",
  Youtube: "youtube",
  Hulu: "hulu",
  Vimeo: "vimeo",
  Animoto: "animoto",
  Dailymotion: "dailymotion",
  Worldstarhiphop: "worldstarhiphop",
  Multi: "multi",
  Sprite: "sprite",
  Text: "text",
  List: "list",
  MediaOptimization: "media_optimization",
} as const;
/**
 * All supported delivery types.
 */
export type DeliveryTypeAllEnum = ClosedEnum<typeof DeliveryTypeAllEnum>;

export const DeliveryTypeAllEnum$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "asset",
  "fetch",
  "url2png",
  "facebook",
  "twitter",
  "twitter_name",
  "instagram",
  "instagram_name",
  "gravatar",
  "youtube",
  "hulu",
  "vimeo",
  "animoto",
  "dailymotion",
  "worldstarhiphop",
  "multi",
  "sprite",
  "text",
  "list",
  "media_optimization",
]).describe("All supported delivery types.");

export type DeleteResourcesByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteResourcesByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteResourcesByPublicIdRequest = {
  resource_type: ResourceType;
  type: DeliveryTypeAllEnum;
  DeleteResourceByPublicIdsRequest: DeleteResourceByPublicIdsRequestUnion;
};

export const DeleteResourcesByPublicIdRequest$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdRequest
> = z.object({
  DeleteResourceByPublicIdsRequest:
    DeleteResourceByPublicIdsRequestUnion$zodSchema.describe(
      "The public IDs and options for the resources to delete.",
    ),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: DeliveryTypeAllEnum$zodSchema.describe(
    "The delivery type of the asset.",
  ),
});

/**
 * Resource successfully deleted
 */
export type DeleteResourcesByPublicIdResponseBody = {};

export const DeleteResourcesByPublicIdResponseBody$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdResponseBody
> = z.object({}).describe("Resource successfully deleted");

export type DeleteResourcesByPublicIdResponse =
  | ApiError
  | DeleteResourcesByPublicIdResponseBody;

export const DeleteResourcesByPublicIdResponse$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => DeleteResourcesByPublicIdResponseBody$zodSchema),
]);

export type GetResourceByPublicIdGlobals = { cloud_name?: string | undefined };

export const GetResourceByPublicIdGlobals$zodSchema: z.ZodType<
  GetResourceByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetResourceByPublicIdRequest = {
  resource_type: ResourceType;
  type: DeliveryTypeAllEnum;
  public_id: string;
  colors?: boolean | undefined;
  media_metadata?: boolean | undefined;
  faces?: boolean | undefined;
  quality_analysis?: boolean | undefined;
  accessibility_analysis?: boolean | undefined;
  pages?: boolean | undefined;
  phash?: boolean | undefined;
  coordinates?: boolean | undefined;
  versions?: boolean | undefined;
  max_results?: number | undefined;
  derived_next_cursor?: string | undefined;
};

export const GetResourceByPublicIdRequest$zodSchema: z.ZodType<
  GetResourceByPublicIdRequest
> = z.object({
  accessibility_analysis: z.boolean().default(false).describe(
    "Whether to return accessibility analysis scores for the image. Default: false.",
  ),
  colors: z.boolean().default(false).describe(
    "Whether to include color information (predominant colors and histogram of 32 leading colors). Default: false.",
  ),
  coordinates: z.boolean().default(false).describe(
    "Whether to include previously specified custom cropping coordinates and faces coordinates. Default: false.",
  ),
  derived_next_cursor: z.string().describe(
    "The cursor for the next page of derived assets when there are more derived images than max_results.",
  ).optional(),
  faces: z.boolean().default(false).describe(
    "Whether to include a list of coordinates of detected faces. Default: false.",
  ),
  max_results: z.int().default(10).describe(
    "Maximum number of derived assets to return. Default: 10.",
  ),
  media_metadata: z.boolean().default(false).describe(
    "Whether to include IPTC, XMP, and detailed Exif metadata in the response. Default: false.",
  ),
  pages: z.boolean().default(false).describe(
    "Whether to report the number of pages in multi-page documents (e.g., PDF). Default: false.",
  ),
  phash: z.boolean().default(false).describe(
    "Whether to include the perceptual hash (pHash) of the uploaded photo for image similarity detection. Default: false.",
  ),
  public_id: z.string().describe("The public ID of the asset."),
  quality_analysis: z.boolean().default(false).describe(
    "Whether to return quality analysis scores for the image. Default: false.",
  ),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: DeliveryTypeAllEnum$zodSchema.describe(
    "The delivery type of the asset.",
  ),
  versions: z.boolean().default(false).describe(
    "Whether to include details of all the backed up versions of the asset. Default: false.",
  ),
});

export type GetResourceByPublicIdResponse = ApiError | Info;

export const GetResourceByPublicIdResponse$zodSchema: z.ZodType<
  GetResourceByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  Info$zodSchema,
]);

export type UpdateResourceByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateResourceByPublicIdGlobals$zodSchema: z.ZodType<
  UpdateResourceByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByPublicIdRequest = {
  resource_type: ResourceType;
  type: DeliveryTypeAllEnum;
  public_id: string;
  ResourceUpdateRequest: ResourceUpdateRequest;
};

export const UpdateResourceByPublicIdRequest$zodSchema: z.ZodType<
  UpdateResourceByPublicIdRequest
> = z.object({
  ResourceUpdateRequest: ResourceUpdateRequest$zodSchema.describe(
    "The asset attributes to update.",
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: DeliveryTypeAllEnum$zodSchema.describe(
    "The delivery type of the asset.",
  ),
});

export type UpdateResourceByPublicIdResponse = ApiError | Info;

export const UpdateResourceByPublicIdResponse$zodSchema: z.ZodType<
  UpdateResourceByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  Info$zodSchema,
]);
