/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cf9aed5b5a91
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DeleteResourceByPublicIdsRequestUnion,
  DeleteResourceByPublicIdsRequestUnion$zodSchema,
} from "./deleteresourcebypublicidsrequestunion.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const DeleteResourcesByPublicIdOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type DeleteResourcesByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const DeleteResourcesByPublicIdGlobals$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteResourcesByPublicIdSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const DeleteResourcesByPublicIdSecurity$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type DeleteResourcesByPublicIdRequest = {
  resource_type: ResourceType;
  type: string;
  DeleteResourceByPublicIdsRequest: DeleteResourceByPublicIdsRequestUnion;
};

export const DeleteResourcesByPublicIdRequest$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdRequest
> = z.object({
  DeleteResourceByPublicIdsRequest:
    DeleteResourceByPublicIdsRequestUnion$zodSchema.describe(
      "The public IDs and options for the resources to delete.",
    ),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: z.string().describe("The delivery type of the asset."),
});

/**
 * Resource successfully deleted
 */
export type DeleteResourcesByPublicIdResponseBody = {};

export const DeleteResourcesByPublicIdResponseBody$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdResponseBody
> = z.object({}).describe("Resource successfully deleted");

export type DeleteResourcesByPublicIdResponse =
  | ApiError
  | DeleteResourcesByPublicIdResponseBody;

export const DeleteResourcesByPublicIdResponse$zodSchema: z.ZodType<
  DeleteResourcesByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => DeleteResourcesByPublicIdResponseBody$zodSchema),
]);
