/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f609f3bcbc44
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export const DeleteResourceByPublicIdsRequestResourceType3 = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export type DeleteResourceByPublicIdsRequestResourceType3 = ClosedEnum<
  typeof DeleteResourceByPublicIdsRequestResourceType3
>;

export const DeleteResourceByPublicIdsRequestResourceType3$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe(
  "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
);

export type DeleteResourceByPublicIdsRequest3 = {
  public_ids?: Array<string> | undefined;
  prefix?: string | undefined;
  all: boolean;
  resource_type?: DeleteResourceByPublicIdsRequestResourceType3 | undefined;
  keep_original?: boolean | undefined;
  invalidate?: boolean | undefined;
  next_cursor?: string | undefined;
  transformations?: string | undefined;
};

export const DeleteResourceByPublicIdsRequest3$zodSchema: z.ZodType<
  DeleteResourceByPublicIdsRequest3
> = z.object({
  all: z.boolean().describe(
    "Delete all assets (of the relevant resource_type and type), including derived assets (up to a maximum of 1000 original resources).",
  ),
  invalidate: z.boolean().default(false).describe(
    "Whether to also invalidate the copies of the resource on the CDN. It usually takes between a few seconds and a few minutes for the invalidation to fully propagate through the CDN. Default: false.",
  ),
  keep_original: z.boolean().default(false).describe(
    "Whether to delete only the derived assets. Default: false.",
  ),
  next_cursor: z.string().optional().describe(
    "(Only when deleting by prefix or all) When a deletion request has more than 1000 resources to delete, the response includes the partial boolean parameter set to true, as well as a next_cursor value. You can then specify this returned next_cursor value as a parameter of the following deletion request.",
  ),
  prefix: z.string().optional().describe(
    "Delete all assets, including derived assets, where the public ID starts with the specified prefix (up to a maximum of 1000 original resources).",
  ),
  public_ids: z.array(z.string()).optional().describe(
    "A list of public IDs of the resources to delete.",
  ),
  resource_type: DeleteResourceByPublicIdsRequestResourceType3$zodSchema
    .default("image").describe(
      "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
    ),
  transformations: z.string().optional().describe(
    "Only the derived assets matching this hash of transformation parameters will be deleted. You can include multiple transformations separated by a pipe character (|).",
  ),
});

/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export const DeleteResourceByPublicIdsRequestResourceType2 = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export type DeleteResourceByPublicIdsRequestResourceType2 = ClosedEnum<
  typeof DeleteResourceByPublicIdsRequestResourceType2
>;

export const DeleteResourceByPublicIdsRequestResourceType2$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe(
  "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
);

export type DeleteResourceByPublicIdsRequest2 = {
  public_ids?: Array<string> | undefined;
  prefix: string;
  all?: boolean | undefined;
  resource_type?: DeleteResourceByPublicIdsRequestResourceType2 | undefined;
  keep_original?: boolean | undefined;
  invalidate?: boolean | undefined;
  next_cursor?: string | undefined;
  transformations?: string | undefined;
};

export const DeleteResourceByPublicIdsRequest2$zodSchema: z.ZodType<
  DeleteResourceByPublicIdsRequest2
> = z.object({
  all: z.boolean().optional().describe(
    "Delete all assets (of the relevant resource_type and type), including derived assets (up to a maximum of 1000 original resources).",
  ),
  invalidate: z.boolean().default(false).describe(
    "Whether to also invalidate the copies of the resource on the CDN. It usually takes between a few seconds and a few minutes for the invalidation to fully propagate through the CDN. Default: false.",
  ),
  keep_original: z.boolean().default(false).describe(
    "Whether to delete only the derived assets. Default: false.",
  ),
  next_cursor: z.string().optional().describe(
    "(Only when deleting by prefix or all) When a deletion request has more than 1000 resources to delete, the response includes the partial boolean parameter set to true, as well as a next_cursor value. You can then specify this returned next_cursor value as a parameter of the following deletion request.",
  ),
  prefix: z.string().describe(
    "Delete all assets, including derived assets, where the public ID starts with the specified prefix (up to a maximum of 1000 original resources).",
  ),
  public_ids: z.array(z.string()).optional().describe(
    "A list of public IDs of the resources to delete.",
  ),
  resource_type: DeleteResourceByPublicIdsRequestResourceType2$zodSchema
    .default("image").describe(
      "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
    ),
  transformations: z.string().optional().describe(
    "Only the derived assets matching this hash of transformation parameters will be deleted. You can include multiple transformations separated by a pipe character (|).",
  ),
});

/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export const DeleteResourceByPublicIdsRequestResourceType1 = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.
 */
export type DeleteResourceByPublicIdsRequestResourceType1 = ClosedEnum<
  typeof DeleteResourceByPublicIdsRequestResourceType1
>;

export const DeleteResourceByPublicIdsRequestResourceType1$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe(
  "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
);

export type DeleteResourceByPublicIdsRequest1 = {
  public_ids: Array<string>;
  prefix?: string | undefined;
  all?: boolean | undefined;
  resource_type?: DeleteResourceByPublicIdsRequestResourceType1 | undefined;
  keep_original?: boolean | undefined;
  invalidate?: boolean | undefined;
  next_cursor?: string | undefined;
  transformations?: string | undefined;
};

export const DeleteResourceByPublicIdsRequest1$zodSchema: z.ZodType<
  DeleteResourceByPublicIdsRequest1
> = z.object({
  all: z.boolean().optional().describe(
    "Delete all assets (of the relevant resource_type and type), including derived assets (up to a maximum of 1000 original resources).",
  ),
  invalidate: z.boolean().default(false).describe(
    "Whether to also invalidate the copies of the resource on the CDN. It usually takes between a few seconds and a few minutes for the invalidation to fully propagate through the CDN. Default: false.",
  ),
  keep_original: z.boolean().default(false).describe(
    "Whether to delete only the derived assets. Default: false.",
  ),
  next_cursor: z.string().optional().describe(
    "(Only when deleting by prefix or all) When a deletion request has more than 1000 resources to delete, the response includes the partial boolean parameter set to true, as well as a next_cursor value. You can then specify this returned next_cursor value as a parameter of the following deletion request.",
  ),
  prefix: z.string().optional().describe(
    "Delete all assets, including derived assets, where the public ID starts with the specified prefix (up to a maximum of 1000 original resources).",
  ),
  public_ids: z.array(z.string()).describe(
    "A list of public IDs of the resources to delete.",
  ),
  resource_type: DeleteResourceByPublicIdsRequestResourceType1$zodSchema
    .default("image").describe(
      "The type of asset. Relevant as a parameter only when using the SDKs (the resource_type is included in the endpoint URL when using the REST API). Note: use video for all video and audio assets, such as .mp3. Default: image.",
    ),
  transformations: z.string().optional().describe(
    "Only the derived assets matching this hash of transformation parameters will be deleted. You can include multiple transformations separated by a pipe character (|).",
  ),
});

/**
 * The delete request specifying which resources to delete.
 */
export type DeleteResourceByPublicIdsRequestUnion =
  | DeleteResourceByPublicIdsRequest1
  | DeleteResourceByPublicIdsRequest2
  | DeleteResourceByPublicIdsRequest3;

export const DeleteResourceByPublicIdsRequestUnion$zodSchema: z.ZodType<
  DeleteResourceByPublicIdsRequestUnion
> = z.union([
  z.lazy(() => DeleteResourceByPublicIdsRequest1$zodSchema),
  z.lazy(() => DeleteResourceByPublicIdsRequest2$zodSchema),
  z.lazy(() => DeleteResourceByPublicIdsRequest3$zodSchema),
]).describe("The delete request specifying which resources to delete.");
