/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50dd1bb1cbdc
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * All possible delivery types.
 */
export const DeliveryTypeAll = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Asset: "asset",
  Fetch: "fetch",
  Url2png: "url2png",
  List: "list",
  Multi: "multi",
  Sprite: "sprite",
  Text: "text",
  Facebook: "facebook",
  Twitter: "twitter",
  TwitterName: "twitter_name",
  Instagram: "instagram",
  InstagramName: "instagram_name",
  Gravatar: "gravatar",
  Youtube: "youtube",
  Hulu: "hulu",
  Vimeo: "vimeo",
  Animoto: "animoto",
  Dailymotion: "dailymotion",
  Worldstarhiphop: "worldstarhiphop",
  Gplus: "gplus",
  Foursquare: "foursquare",
  MediaOptimization: "media_optimization",
} as const;
/**
 * All possible delivery types.
 */
export type DeliveryTypeAll = ClosedEnum<typeof DeliveryTypeAll>;

export const DeliveryTypeAll$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "asset",
  "fetch",
  "url2png",
  "list",
  "multi",
  "sprite",
  "text",
  "facebook",
  "twitter",
  "twitter_name",
  "instagram",
  "instagram_name",
  "gravatar",
  "youtube",
  "hulu",
  "vimeo",
  "animoto",
  "dailymotion",
  "worldstarhiphop",
  "gplus",
  "foursquare",
  "media_optimization",
]).describe("All possible delivery types.");
