/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const Deleted = {
  Deleted: "deleted",
  NotFound: "not_found",
} as const;
export type Deleted = ClosedEnum<typeof Deleted>;

export const Deleted$zodSchema = z.enum([
  "deleted",
  "not_found",
]);

export type Invalidation = {
  took?: number | undefined;
  urls?: Array<string> | undefined;
};

export const Invalidation$zodSchema: z.ZodType<Invalidation> = z.object({
  took: z.number().optional(),
  urls: z.array(z.string()).optional(),
});

/**
 * Response for derived resource deletion
 */
export type DerivedDestroyResponse = {
  deleted?: { [k: string]: Deleted } | undefined;
  unauthorized?: Array<string> | undefined;
  invalidation?: Invalidation | undefined;
};

export const DerivedDestroyResponse$zodSchema: z.ZodType<
  DerivedDestroyResponse
> = z.object({
  deleted: z.record(z.string(), Deleted$zodSchema).optional(),
  invalidation: z.lazy(() => Invalidation$zodSchema).optional(),
  unauthorized: z.array(z.string()).optional(),
}).describe("Response for derived resource deletion");
