/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d820256ef5c9
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The result of the deletion operation.
 */
export const Result = {
  Ok: "ok",
  NotFound: "not found",
} as const;
/**
 * The result of the deletion operation.
 */
export type Result = ClosedEnum<typeof Result>;

export const Result$zodSchema = z.enum([
  "ok",
  "not found",
]).describe("The result of the deletion operation.");

export type DestroyResponse = {
  result: Result;
  asset_folder?: string | undefined;
};

export const DestroyResponse$zodSchema: z.ZodType<DestroyResponse> = z.object({
  asset_folder: z.string().optional().describe(
    "The asset folder path. Only included when folder decoupling is enabled.",
  ),
  result: Result$zodSchema.describe("The result of the deletion operation."),
});
