/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8fc9b24c0973
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The result of the deletion operation.
 */
export const DestroyByAssetIdResponseResult = {
  Ok: "ok",
  NotFound: "not found",
} as const;
/**
 * The result of the deletion operation.
 */
export type DestroyByAssetIdResponseResult = ClosedEnum<
  typeof DestroyByAssetIdResponseResult
>;

export const DestroyByAssetIdResponseResult$zodSchema = z.enum([
  "ok",
  "not found",
]).describe("The result of the deletion operation.");

export type DestroyByAssetIdResponse = {
  result: DestroyByAssetIdResponseResult;
};

export const DestroyByAssetIdResponse$zodSchema: z.ZodType<
  DestroyByAssetIdResponse
> = z.object({
  result: DestroyByAssetIdResponseResult$zodSchema.describe(
    "The result of the deletion operation.",
  ),
});
