/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 34d4c54fd9b8
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  DestroyByAssetIdResponse,
  DestroyByAssetIdResponse$zodSchema,
} from "./destroybyassetidresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const DestroyByAssetIdOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type DestroyByAssetIdGlobals = { cloud_name?: string | undefined };

export const DestroyByAssetIdGlobals$zodSchema: z.ZodType<
  DestroyByAssetIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DestroyByAssetIdSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const DestroyByAssetIdSecurity$zodSchema: z.ZodType<
  DestroyByAssetIdSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type DestroyByAssetIdResponseResponse =
  | DestroyByAssetIdResponse
  | ApiError;

export const DestroyByAssetIdResponseResponse$zodSchema: z.ZodType<
  DestroyByAssetIdResponseResponse
> = z.union([
  DestroyByAssetIdResponse$zodSchema,
  ApiError$zodSchema,
]);
