/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e7dc5212a339
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type EvalUploadParamsGlobals = { cloud_name?: string | undefined };

export const EvalUploadParamsGlobals$zodSchema: z.ZodType<
  EvalUploadParamsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type EvalUploadParamsResponse = ApiError | { [k: string]: any };

export const EvalUploadParamsResponse$zodSchema: z.ZodType<
  EvalUploadParamsResponse
> = z.union([
  ApiError$zodSchema,
  z.record(z.string(), z.any()).describe("The evaluated upload parameters."),
]);
