/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c601a72cb920
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";

/**
 * The eval expression and the upload parameters to evaluate it against. The `eval` field holds
 *
 * @remarks
 * the dynamic expression; any other upload parameters may be supplied alongside it.
 */
export type EvalRequest = {
  eval: string;
  public_id?: string | undefined;
  AdditionalProperties?: { [k: string]: any };
};

export const EvalRequest$zodSchema: z.ZodType<EvalRequest> = collectExtraKeys$(
  z.object({
    eval: z.string().describe(
      "The dynamic eval expression to evaluate against the upload parameters.",
    ),
    public_id: z.string().optional().describe(
      "The public ID of the asset the eval expression applies to.",
    ),
  }).describe(
    "The eval expression and the upload parameters to evaluate it against. The `eval` field holds\nthe dynamic expression; any other upload parameters may be supplied alongside it.\n",
  ).catchall(z.any()),
  "AdditionalProperties",
  true,
);

export const EvalRequest$zodSchemaOutbound: z.ZodType<any> = z.object({
  AdditionalProperties: z.record(z.string(), z.any()).optional(),
  eval: z.string(),
  public_id: z.string().optional(),
}).describe(
  "The eval expression and the upload parameters to evaluate it against. The `eval` field holds\nthe dynamic expression; any other upload parameters may be supplied alongside it.\n",
).transform((v) => {
  const { AdditionalProperties, ...rest } = v;
  return {
    ...rest,
    ...AdditionalProperties,
  };
});
