/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5b8dcd950c40
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { ExplodeRequest, ExplodeRequest$zodSchema } from "./exploderequest.js";
import {
  ExplodeResponse,
  ExplodeResponse$zodSchema,
} from "./exploderesponse.js";

export type ExplodeResourceGlobals = { cloud_name?: string | undefined };

export const ExplodeResourceGlobals$zodSchema: z.ZodType<
  ExplodeResourceGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * The type of resource to explode. Only "image" is supported.
 */
export const ExplodeResourceResourceType = {
  Image: "image",
} as const;
/**
 * The type of resource to explode. Only "image" is supported.
 */
export type ExplodeResourceResourceType = ClosedEnum<
  typeof ExplodeResourceResourceType
>;

export const ExplodeResourceResourceType$zodSchema = z.enum([
  "image",
]).describe("The type of resource to explode. Only \"image\" is supported.");

export type ExplodeResourceRequest = {
  resource_type: ExplodeResourceResourceType;
  explode_request: ExplodeRequest;
};

export const ExplodeResourceRequest$zodSchema: z.ZodType<
  ExplodeResourceRequest
> = z.object({
  explode_request: ExplodeRequest$zodSchema.describe(
    "The explode operation parameters.",
  ),
  resource_type: ExplodeResourceResourceType$zodSchema.describe(
    "The type of resource to explode. Only \"image\" is supported.",
  ),
});

export type ExplodeResourceResponse = ApiError | ExplodeResponse;

export const ExplodeResourceResponse$zodSchema: z.ZodType<
  ExplodeResourceResponse
> = z.union([
  ApiError$zodSchema,
  ExplodeResponse$zodSchema,
]);
