/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ArchiveStorageType,
  ArchiveStorageType$zodSchema,
} from "./archivestoragetype.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export type ExplicitAssetGlobals = { cloud_name?: string | undefined };

export const ExplicitAssetGlobals$zodSchema: z.ZodType<ExplicitAssetGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

/**
 * Configuration object for automatic video transcription with translation options.
 */
export type ExplicitAssetAutoTranscription = {
  translate?: Array<string> | undefined;
};

export const ExplicitAssetAutoTranscription$zodSchema: z.ZodType<
  ExplicitAssetAutoTranscription
> = z.object({
  translate: z.array(z.string()).optional(),
}).describe(
  "Configuration object for automatic video transcription with translation options.",
);

export type ExplicitAssetAutoTranscriptionUnion =
  | boolean
  | ExplicitAssetAutoTranscription;

export const ExplicitAssetAutoTranscriptionUnion$zodSchema: z.ZodType<
  ExplicitAssetAutoTranscriptionUnion
> = z.union([
  z.boolean(),
  z.lazy(() => ExplicitAssetAutoTranscription$zodSchema),
]);

export type ExplicitAssetResponsiveBreakpoint = {
  create_derived?: boolean | undefined;
  max_width?: number | undefined;
  min_width?: number | undefined;
  bytes_step?: number | undefined;
  max_images?: number | undefined;
  transformation?: string | undefined;
};

export const ExplicitAssetResponsiveBreakpoint$zodSchema: z.ZodType<
  ExplicitAssetResponsiveBreakpoint
> = z.object({
  bytes_step: z.int().optional(),
  create_derived: z.boolean().optional(),
  max_images: z.int().optional(),
  max_width: z.int().optional(),
  min_width: z.int().optional(),
  transformation: z.string().optional(),
});

/**
 * Override the quality setting for this asset.
 */
export type QualityOverride = string | number;

export const QualityOverride$zodSchema: z.ZodType<QualityOverride> = z.union([
  z.string(),
  z.int(),
]).describe("Override the quality setting for this asset.");

export type ExplicitAssetRequestBody = {
  api_key?: string | undefined;
  timestamp?: number | undefined;
  signature?: string | undefined;
  accessibility_analysis?: boolean | undefined;
  asset_folder?: string | undefined;
  async?: boolean | undefined;
  auto_chaptering?: boolean | undefined;
  auto_transcription?: boolean | ExplicitAssetAutoTranscription | undefined;
  cinemagraph_analysis?: boolean | undefined;
  colors?: boolean | undefined;
  context?: string | undefined;
  custom_coordinates?: string | undefined;
  display_name?: string | undefined;
  eager?: string | undefined;
  eager_async?: boolean | undefined;
  eager_notification_url?: string | undefined;
  face_coordinates?: string | undefined;
  faces?: boolean | undefined;
  headers?: string | undefined;
  invalidate?: boolean | undefined;
  media_metadata?: boolean | undefined;
  metadata?: string | undefined;
  moderation?: string | undefined;
  notification_url?: string | undefined;
  phash?: boolean | undefined;
  quality_analysis?: boolean | undefined;
  regions?: string | undefined;
  responsive_breakpoints?: Array<ExplicitAssetResponsiveBreakpoint> | undefined;
  tags?: string | undefined;
  callback?: string | undefined;
  public_id: string;
  type?: ArchiveStorageType | undefined;
  overwrite?: boolean | undefined;
  quality_override?: string | number | undefined;
};

export const ExplicitAssetRequestBody$zodSchema: z.ZodType<
  ExplicitAssetRequestBody
> = z.object({
  accessibility_analysis: z.boolean().optional(),
  api_key: z.string().optional(),
  asset_folder: z.string().optional(),
  async: z.boolean().optional(),
  auto_chaptering: z.boolean().optional(),
  auto_transcription: z.union([
    z.boolean(),
    z.lazy(() => ExplicitAssetAutoTranscription$zodSchema),
  ]).optional(),
  callback: z.string().optional(),
  cinemagraph_analysis: z.boolean().optional(),
  colors: z.boolean().default(false),
  context: z.string().optional(),
  custom_coordinates: z.string().optional(),
  display_name: z.string().optional(),
  eager: z.string().optional(),
  eager_async: z.boolean().optional(),
  eager_notification_url: z.string().optional(),
  face_coordinates: z.string().optional(),
  faces: z.boolean().optional(),
  headers: z.string().optional(),
  invalidate: z.boolean().optional(),
  media_metadata: z.boolean().optional(),
  metadata: z.string().optional(),
  moderation: z.string().optional(),
  notification_url: z.string().optional(),
  overwrite: z.boolean().optional(),
  phash: z.boolean().optional(),
  public_id: z.string(),
  quality_analysis: z.boolean().optional(),
  quality_override: z.union([
    z.string(),
    z.int(),
  ]).optional(),
  regions: z.string().optional(),
  responsive_breakpoints: z.array(
    z.lazy(() => ExplicitAssetResponsiveBreakpoint$zodSchema),
  ).optional(),
  signature: z.string().optional(),
  tags: z.string().optional(),
  timestamp: z.int().optional(),
  type: ArchiveStorageType$zodSchema.optional(),
});

export type ExplicitAssetRequest = {
  resource_type: ResourceType;
  RequestBody: ExplicitAssetRequestBody;
};

export const ExplicitAssetRequest$zodSchema: z.ZodType<ExplicitAssetRequest> = z
  .object({
    RequestBody: z.lazy(() => ExplicitAssetRequestBody$zodSchema),
    resource_type: ResourceType$zodSchema,
  });

export type ExplicitAssetResponse = ApiError | UploadResponse;

export const ExplicitAssetResponse$zodSchema: z.ZodType<ExplicitAssetResponse> =
  z.union([
    ApiError$zodSchema,
    UploadResponse$zodSchema,
  ]);
