/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb083d67962d
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of the explode operation.
 */
export const ExplodeResponseStatus = {
  Processing: "processing",
} as const;
/**
 * The status of the explode operation.
 */
export type ExplodeResponseStatus = ClosedEnum<typeof ExplodeResponseStatus>;

export const ExplodeResponseStatus$zodSchema = z.enum([
  "processing",
]).describe("The status of the explode operation.");

export type ExplodeResponse = {
  status?: ExplodeResponseStatus | undefined;
  batch_id?: string | undefined;
};

export const ExplodeResponse$zodSchema: z.ZodType<ExplodeResponse> = z.object({
  batch_id: z.string().optional().describe("The ID of the batch operation."),
  status: ExplodeResponseStatus$zodSchema.optional().describe(
    "The status of the explode operation.",
  ),
});
