/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 61e54c9b6b8c
 */

import * as z from "zod";

/**
 * The source and destination folder paths.
 */
export type FolderRenameRequest = {
  path: string;
  to_path: string;
  resources_limit?: number | undefined;
  resources_size_limit?: number | undefined;
  max_derived?: number | undefined;
};

export const FolderRenameRequest$zodSchema: z.ZodType<FolderRenameRequest> = z
  .object({
    max_derived: z.int().optional().describe(
      "The maximum number of derived assets that may be moved by the rename.",
    ),
    path: z.string().describe("The full path of the folder to rename or move."),
    resources_limit: z.int().optional().describe(
      "The maximum number of assets that may be moved by the rename. Assets beyond this limit cause the rename to be rejected.",
    ),
    resources_size_limit: z.int().optional().describe(
      "The maximum total size, in bytes, of the assets that may be moved by the rename.",
    ),
    to_path: z.string().describe("The new full path for the folder."),
  }).describe("The source and destination folder paths.");
