/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 164b01265596
 */

import * as z from "zod";

export type FolderRole = {
  id: string;
  name: string;
  description: string;
  inherited: boolean;
};

export const FolderRole$zodSchema: z.ZodType<FolderRole> = z.object({
  description: z.string().describe(
    "A summary of the permissions granted by this role.",
  ),
  id: z.string().describe("The unique identifier of the role."),
  inherited: z.boolean().describe(
    "Indicates whether this role is inherited from an ancestor folder. If false, it's assigned directly to the requested folder.",
  ),
  name: z.string().describe("The human-readable name of the role."),
});
