/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Folder = {
  name: string;
  path: string;
  external_id: string;
  created_at?: string | undefined;
};

export const Folder$zodSchema: z.ZodType<Folder> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  external_id: z.string(),
  name: z.string(),
  path: z.string(),
});
