/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9f7e976d9b5b
 */

import * as z from "zod";

/**
 * The path of the folder to retrieve.
 */
export type FolderByPathRequest = {
  path: string;
  case_sensitive?: boolean | undefined;
};

export const FolderByPathRequest$zodSchema: z.ZodType<FolderByPathRequest> = z
  .object({
    case_sensitive: z.boolean().optional().describe(
      "Whether to match the folder path case-sensitively. If false, the path is matched case-insensitively.",
    ),
    path: z.string().describe(
      "The full path of the folder to retrieve. Use an empty string for the root folder.",
    ),
  }).describe("The path of the folder to retrieve.");
