/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a303d53836d0
 */

import * as z from "zod";
import {
  FolderRoleAssignment,
  FolderRoleAssignment$zodSchema,
} from "./folderroleassignment.js";
import { PermittedRole, PermittedRole$zodSchema } from "./permittedrole.js";

export type FolderRolesResponse = {
  shared_with?: Array<FolderRoleAssignment> | undefined;
  permitted_roles?: Array<PermittedRole> | undefined;
};

export const FolderRolesResponse$zodSchema: z.ZodType<FolderRolesResponse> = z
  .object({
    permitted_roles: z.array(PermittedRole$zodSchema).optional().describe(
      "The roles the authenticated user can assign on this folder. Users can assign only roles at or below their own permission level for this folder. Returned only when `include_assignable_roles` is true.",
    ),
    shared_with: z.array(FolderRoleAssignment$zodSchema).optional().describe(
      "An array of principals (users, groups, or API keys) with their role assignments on this folder, including roles inherited from ancestor folders.",
    ),
  });
