/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ef2ec9481507
 */

import * as z from "zod";
import {
  FolderDetailResponse,
  FolderDetailResponse$zodSchema,
} from "./folderdetailresponse.js";

/**
 * The descendant folders of a folder.
 */
export type FolderDescendantsResponse = {
  folders: Array<FolderDetailResponse>;
};

export const FolderDescendantsResponse$zodSchema: z.ZodType<
  FolderDescendantsResponse
> = z.object({
  folders: z.array(FolderDetailResponse$zodSchema).describe(
    "The descendant folders.",
  ),
}).describe("The descendant folders of a folder.");
