/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ec149afd0d1b
 */

import * as z from "zod";

/**
 * The identifier of the folder to retrieve.
 */
export type FolderByIdRequest = { id: string };

export const FolderByIdRequest$zodSchema: z.ZodType<FolderByIdRequest> = z
  .object({
    id: z.string().describe(
      "The immutable identifier of the folder to retrieve.",
    ),
  }).describe("The identifier of the folder to retrieve.");
