/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b5abb32aaca9
 */

import * as z from "zod";
import { FolderRole, FolderRole$zodSchema } from "./folderrole.js";
import { PrincipalType, PrincipalType$zodSchema } from "./principaltype.js";

export type FolderRoleAssignment = {
  type: PrincipalType;
  id: string;
  folder_id: string;
  roles: Array<FolderRole>;
};

export const FolderRoleAssignment$zodSchema: z.ZodType<FolderRoleAssignment> = z
  .object({
    folder_id: z.string().describe(
      "The ID of the folder where this role assignment was defined, either the requested folder or one of its ancestor folders.",
    ),
    id: z.string().describe(
      "The unique identifier of the principal. For `apiKey`, provide the API key value.",
    ),
    roles: z.array(FolderRole$zodSchema).describe(
      "The roles assigned to this principal for this folder.",
    ),
    type: PrincipalType$zodSchema.describe("The type of principal."),
  });
