/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f383f1adbc7d
 */

import * as z from "zod";

/**
 * The parent folder identifier and optional descendant filter.
 */
export type FolderDescendantsRequest = {
  id: string;
  filter_ids?: Array<string> | undefined;
  inclusive?: boolean | undefined;
};

export const FolderDescendantsRequest$zodSchema: z.ZodType<
  FolderDescendantsRequest
> = z.object({
  filter_ids: z.array(z.string()).optional().describe(
    "A list of folder identifiers to restrict the returned descendants to.",
  ),
  id: z.string().describe(
    "The immutable identifier of the parent folder whose descendants are returned.",
  ),
  inclusive: z.boolean().optional().describe(
    "Whether to include the parent folder itself in the results. If false, only descendants are returned.",
  ),
}).describe("The parent folder identifier and optional descendant filter.");
