/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c28b0f5b136
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ArchiveResourceType,
  ArchiveResourceType$zodSchema,
} from "./archiveresourcetype.js";
import {
  GenerateArchiveRequest,
  GenerateArchiveRequest$zodSchema,
} from "./generatearchiverequest.js";
import {
  GenerateArchiveResponse,
  GenerateArchiveResponse$zodSchema,
} from "./generatearchiveresponse.js";

export type GenerateArchiveGlobals = { cloud_name?: string | undefined };

export const GenerateArchiveGlobals$zodSchema: z.ZodType<
  GenerateArchiveGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GenerateArchiveRequestRequest = {
  resource_type: ArchiveResourceType;
  generate_archive_request: GenerateArchiveRequest;
};

export const GenerateArchiveRequestRequest$zodSchema: z.ZodType<
  GenerateArchiveRequestRequest
> = z.object({
  generate_archive_request: GenerateArchiveRequest$zodSchema.describe(
    "The archive generation parameters.",
  ),
  resource_type: ArchiveResourceType$zodSchema.describe(
    "The type of resource for archive generation (image, video, or raw).",
  ),
});

export type GenerateArchiveResponseResponse =
  | ApiError
  | Uint8Array
  | string
  | GenerateArchiveResponse;

export const GenerateArchiveResponseResponse$zodSchema: z.ZodType<
  GenerateArchiveResponseResponse
> = z.union([
  ApiError$zodSchema,
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  GenerateArchiveResponse$zodSchema,
]);
