/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 958825c984f2
 */

import * as z from "zod";
import { ImageFormat, ImageFormat$zodSchema } from "./imageformat.js";
import { ImageSize, ImageSize$zodSchema } from "./imagesize.js";
import { ModelSelection, ModelSelection$zodSchema } from "./modelselection.js";
import { Target, Target$zodSchema } from "./target.js";

/**
 * Parameters for an image-generation request. Only `prompt` is required;
 *
 * @remarks
 * all other fields fall back to documented defaults.
 */
export type GenerateImageRequest = {
  prompt: string;
  model?: ModelSelection | undefined;
  image_size?: ImageSize | undefined;
  format?: ImageFormat | undefined;
  target?: Target | undefined;
  seed?: number | null | undefined;
  async?: boolean | undefined;
  notification_url?: string | undefined;
};

export const GenerateImageRequest$zodSchema: z.ZodType<GenerateImageRequest> = z
  .object({
    async: z.boolean().default(false).describe(
      "Whether to perform the generation asynchronously. When true, the API\nreturns immediately with a 202 and completes in the background. Once\ncomplete, a webhook notification is sent to the specified URL and/or to\nthe URLs defined in the product environment's settings.\n",
    ),
    format: ImageFormat$zodSchema.optional().describe(
      "Desired output image format. Optional; defaults to `png` when omitted.\nMapped to the closest format the chosen model supports — `webp` falls\nback to `png` on models that don't support it (e.g. FLUX.2 Pro), and the\nrequest is ignored entirely by models that don't expose a format option\n(e.g. Recraft).\n",
    ),
    image_size: ImageSize$zodSchema.optional().describe(
      "Desired output size, given in **one** of two mutually exclusive forms:\n\n  * `DimensionsImageSize`: `width` and `height` in pixels, for precise\n    control.\n  * `DeclarativeImageSize`: `aspect_ratio` (and an optional `resolution`\n    tier), resolved server-side to the closest size the chosen model\n    supports. This is the portable form: most providers natively accept\n    an aspect ratio plus a resolution tier rather than raw pixels.\n\nOmit `image_size` entirely to use the model's default size.\n",
    ),
    model: ModelSelection$zodSchema.optional().describe(
      "Selects the model, in one of three mutually exclusive forms (omit to use\nthe global default):\n  * `ModelByFamily`: `family` (+ optional `tier`); the stable-over-time\n    selector.\n  * `ModelById`: an explicit `id`, pinning one exact model.\n  * `ModelAuto`: `mode: auto`, letting the service choose the model for\n    the request (+ optional `preference`).\n",
    ),
    notification_url: z.string().optional().describe(
      "The webhook URL to notify when the generation is complete. Only relevant when `async` is set to true.",
    ),
    prompt: z.string().describe(
      "The text description of the image to generate.",
    ),
    seed: z.int().nullable().optional().describe(
      "Seed for reproducible generation. Supported by the `flux`, `nano-banana`\nand `ideogram` models and by `qwen-image-3`; silently ignored by the\nmodels that don't support it, which report `seed` as null in the\nresponse.\n",
    ),
    target: Target$zodSchema.optional().describe(
      "Where to store the generated output, determined by `target_type`.\nOptional; defaults to a `managed_asset` target when omitted.\n",
    ),
  }).describe(
    "Parameters for an image-generation request. Only `prompt` is required;\nall other fields fall back to documented defaults.\n",
  );
