/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e12fe2235ff8
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderDescendantsResponse,
  FolderDescendantsResponse$zodSchema,
} from "./folderdescendantsresponse.js";

export type GetFolderDescendantsGlobals = { cloud_name?: string | undefined };

export const GetFolderDescendantsGlobals$zodSchema: z.ZodType<
  GetFolderDescendantsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetFolderDescendantsResponse = FolderDescendantsResponse | ApiError;

export const GetFolderDescendantsResponse$zodSchema: z.ZodType<
  GetFolderDescendantsResponse
> = z.union([
  FolderDescendantsResponse$zodSchema,
  ApiError$zodSchema,
]);
