/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ab81aa86a9e
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderDetailResponse,
  FolderDetailResponse$zodSchema,
} from "./folderdetailresponse.js";

export type GetFolderByPathGlobals = { cloud_name?: string | undefined };

export const GetFolderByPathGlobals$zodSchema: z.ZodType<
  GetFolderByPathGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetFolderByPathResponse = FolderDetailResponse | ApiError;

export const GetFolderByPathResponse$zodSchema: z.ZodType<
  GetFolderByPathResponse
> = z.union([
  FolderDetailResponse$zodSchema,
  ApiError$zodSchema,
]);
