/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: faeba8b81c93
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderDetailResponse,
  FolderDetailResponse$zodSchema,
} from "./folderdetailresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const GetFolderByIdOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type GetFolderByIdGlobals = { cloud_name?: string | undefined };

export const GetFolderByIdGlobals$zodSchema: z.ZodType<GetFolderByIdGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type GetFolderByIdSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const GetFolderByIdSecurity$zodSchema: z.ZodType<GetFolderByIdSecurity> =
  z.object({
    cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
    oauth2: z.string().describe(
      "OAuth2 Authorization Code flow for user authentication",
    ).optional(),
  });

export type GetFolderByIdResponse = FolderDetailResponse | ApiError;

export const GetFolderByIdResponse$zodSchema: z.ZodType<GetFolderByIdResponse> =
  z.union([
    FolderDetailResponse$zodSchema,
    ApiError$zodSchema,
  ]);
