/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e12fe2235ff8
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderDescendantsResponse,
  FolderDescendantsResponse$zodSchema,
} from "./folderdescendantsresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const GetFolderDescendantsOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type GetFolderDescendantsGlobals = { cloud_name?: string | undefined };

export const GetFolderDescendantsGlobals$zodSchema: z.ZodType<
  GetFolderDescendantsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetFolderDescendantsSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const GetFolderDescendantsSecurity$zodSchema: z.ZodType<
  GetFolderDescendantsSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type GetFolderDescendantsResponse = FolderDescendantsResponse | ApiError;

export const GetFolderDescendantsResponse$zodSchema: z.ZodType<
  GetFolderDescendantsResponse
> = z.union([
  FolderDescendantsResponse$zodSchema,
  ApiError$zodSchema,
]);
