/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ab81aa86a9e
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderDetailResponse,
  FolderDetailResponse$zodSchema,
} from "./folderdetailresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const GetFolderByPathOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type GetFolderByPathGlobals = { cloud_name?: string | undefined };

export const GetFolderByPathGlobals$zodSchema: z.ZodType<
  GetFolderByPathGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetFolderByPathSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const GetFolderByPathSecurity$zodSchema: z.ZodType<
  GetFolderByPathSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type GetFolderByPathResponse = FolderDetailResponse | ApiError;

export const GetFolderByPathResponse$zodSchema: z.ZodType<
  GetFolderByPathResponse
> = z.union([
  FolderDetailResponse$zodSchema,
  ApiError$zodSchema,
]);
