/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3681227fdc16
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { PersonResponse, PersonResponse$zodSchema } from "./personresponse.js";

export const GetPersonOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type GetPersonGlobals = { cloud_name?: string | undefined };

export const GetPersonGlobals$zodSchema: z.ZodType<GetPersonGlobals> = z.object(
  {
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  },
);

export type GetPersonRequest = { person_id: string };

export const GetPersonRequest$zodSchema: z.ZodType<GetPersonRequest> = z.object(
  {
    person_id: z.string().describe("The unique identifier of the person."),
  },
);

export type GetPersonResponse = ApiError | PersonResponse;

export const GetPersonResponse$zodSchema: z.ZodType<GetPersonResponse> = z
  .union([
    ApiError$zodSchema,
    PersonResponse$zodSchema,
  ]);
