/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4640cf9de480
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ResourceInternalResponse,
  ResourceInternalResponse$zodSchema,
} from "./resourceinternalresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const GetResourceByBodyOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type GetResourceByBodyGlobals = { cloud_name?: string | undefined };

export const GetResourceByBodyGlobals$zodSchema: z.ZodType<
  GetResourceByBodyGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetResourceByBodySecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const GetResourceByBodySecurity$zodSchema: z.ZodType<
  GetResourceByBodySecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type GetResourceByBodyResponse = ApiError | ResourceInternalResponse;

export const GetResourceByBodyResponse$zodSchema: z.ZodType<
  GetResourceByBodyResponse
> = z.union([
  ApiError$zodSchema,
  ResourceInternalResponse$zodSchema,
]);
