/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type GetVideoViewsGlobals = { cloud_name?: string | undefined };

export const GetVideoViewsGlobals$zodSchema: z.ZodType<GetVideoViewsGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

/**
 * Specifies the expression field by which to sort the results. Prepend values with a '-' to reverse the order.
 */
export const GetVideoViewsSortBy = {
  ViewEndedAt: "view_ended_at",
  VideoDuration: "video_duration",
  ViewWatchTime: "view_watch_time",
  MinusViewEndedAt: "-view_ended_at",
  MinusVideoDuration: "-video_duration",
  MinusViewWatchTime: "-view_watch_time",
} as const;
/**
 * Specifies the expression field by which to sort the results. Prepend values with a '-' to reverse the order.
 */
export type GetVideoViewsSortBy = ClosedEnum<typeof GetVideoViewsSortBy>;

export const GetVideoViewsSortBy$zodSchema = z.enum([
  "view_ended_at",
  "video_duration",
  "view_watch_time",
  "-view_ended_at",
  "-video_duration",
  "-view_watch_time",
]).describe(
  "Specifies the expression field by which to sort the results. Prepend values with a '-' to reverse the order.",
);

export type GetVideoViewsRequest = {
  expression?: string | undefined;
  max_results?: number | undefined;
  sort_by?: GetVideoViewsSortBy | undefined;
  next_cursor?: string | undefined;
};

export const GetVideoViewsRequest$zodSchema: z.ZodType<GetVideoViewsRequest> = z
  .object({
    expression: z.string().describe(
      "A set of conditions used to limit the results to rows that match those conditions. For example: `?expression=video_public_id=skate`",
    ).optional(),
    max_results: z.int().default(10).describe(
      "The maximum number of results to return. Default is 10.",
    ),
    next_cursor: z.string().describe(
      "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
    ).optional(),
    sort_by: GetVideoViewsSortBy$zodSchema.default("-view_ended_at"),
  });

export type Data = {
  video_public_id?: string | undefined;
  video_duration?: number | null | undefined;
  video_transformation?: string | null | undefined;
  video_extension?: string | null | undefined;
  viewer_application_name?: string | null | undefined;
  viewer_location_country_code?: string | null | undefined;
  viewer_os_identifier?: string | null | undefined;
  view_watch_time?: number | null | undefined;
  view_ended_at?: string | undefined;
};

export const Data$zodSchema: z.ZodType<Data> = z.object({
  video_duration: z.number().nullable().optional(),
  video_extension: z.string().nullable().optional(),
  video_public_id: z.string().optional(),
  video_transformation: z.string().nullable().optional(),
  view_ended_at: z.iso.datetime({ offset: true }).optional(),
  view_watch_time: z.number().nullable().optional(),
  viewer_application_name: z.string().nullable().optional(),
  viewer_location_country_code: z.string().nullable().optional(),
  viewer_os_identifier: z.string().nullable().optional(),
});

/**
 * List of video views retrieved
 */
export type GetVideoViewsResponseBody = {
  request_id?: string | undefined;
  next_cursor?: string | undefined;
  data?: Array<Data> | undefined;
};

export const GetVideoViewsResponseBody$zodSchema: z.ZodType<
  GetVideoViewsResponseBody
> = z.object({
  data: z.array(z.lazy(() => Data$zodSchema)).optional(),
  next_cursor: z.string().optional(),
  request_id: z.string().optional(),
}).describe("List of video views retrieved");

export type GetVideoViewsResponse = ApiError | GetVideoViewsResponseBody;

export const GetVideoViewsResponse$zodSchema: z.ZodType<GetVideoViewsResponse> =
  z.union([
    ApiError$zodSchema,
    z.lazy(() => GetVideoViewsResponseBody$zodSchema),
  ]);
