/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 70f4d95abf4e
 */

import * as z from "zod";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";

export type InfoContext2 = {
  key?: string | undefined;
  value?: string | undefined;
};

export const InfoContext2$zodSchema: z.ZodType<InfoContext2> = z.object({
  key: z.string().optional(),
  value: z.string().optional(),
});

export type InfoContext1 = { custom?: { [k: string]: any } | undefined };

export const InfoContext1$zodSchema: z.ZodType<InfoContext1> = z.object({
  custom: z.record(z.string(), z.any()).optional(),
});

/**
 * Included if 'context=true' parameter is used. Can be object with custom properties or array of key-value pairs.
 */
export type Context = InfoContext1 | Array<InfoContext2>;

export const Context$zodSchema: z.ZodType<Context> = z.union([
  z.lazy(() => InfoContext1$zodSchema),
  z.array(z.lazy(() => InfoContext2$zodSchema)),
]).describe(
  "Included if 'context=true' parameter is used. Can be object with custom properties or array of key-value pairs.",
);

export type Moderation = {
  kind?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

export const Moderation$zodSchema: z.ZodType<Moderation> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
});

export type RelatedAsset = {};

export const RelatedAsset$zodSchema: z.ZodType<RelatedAsset> = z.object({});

export type Derivative = {
  id?: string | undefined;
  transformation?: string | undefined;
  transformation_signature?: string | undefined;
  secure_url?: string | undefined;
};

export const Derivative$zodSchema: z.ZodType<Derivative> = z.object({
  id: z.string().optional().describe(
    "The unique identifier of the derived resource",
  ),
  secure_url: z.string().optional().describe(
    "The secure URL for accessing the derived resource",
  ),
  transformation: z.string().optional().describe(
    "The transformation string that was applied",
  ),
  transformation_signature: z.string().optional().describe(
    "The unique signature of the transformation",
  ),
});

export type Info = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  asset_folder?: string | undefined;
  display_name?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resource_type?: string | undefined;
  type?: string | undefined;
  created_at?: string | undefined;
  uploaded_at?: string | undefined;
  bytes?: number | undefined;
  backup_bytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspect_ratio?: number | null | undefined;
  pixels?: number | null | undefined;
  tags?: Array<string> | null | undefined;
  context?: InfoContext1 | Array<InfoContext2> | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  moderation_kind?: string | undefined;
  moderation_status?: string | undefined;
  moderation?: Array<Moderation> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  status?: string | undefined;
  access_control?: Array<AccessControlItem> | null | undefined;
  etag?: string | undefined;
  animated?: boolean | null | undefined;
  duration?: number | null | undefined;
  resource_subtype?: string | null | undefined;
  substatus?: string | null | undefined;
  related_assets?: Array<RelatedAsset> | null | undefined;
  derivatives?: Array<Derivative> | null | undefined;
};

export const Info$zodSchema: z.ZodType<Info> = z.object({
  access_control: z.array(AccessControlItem$zodSchema).nullable().optional(),
  animated: z.boolean().nullable().optional().describe(
    "Whether the asset is animated (e.g., GIF, animated WebP). Null for non-animated assets.",
  ),
  aspect_ratio: z.number().nullable().optional(),
  asset_folder: z.string().optional(),
  asset_id: z.string().optional(),
  backup: z.boolean().optional(),
  backup_bytes: z.int().optional(),
  bytes: z.int().optional(),
  context: z.union([
    z.lazy(() => InfoContext1$zodSchema),
    z.array(z.lazy(() => InfoContext2$zodSchema)),
  ]).nullable().optional().describe(
    "Included if 'context=true' parameter is used. Can be object with custom properties or array of key-value pairs.",
  ),
  created_at: z.iso.datetime({ offset: true }).optional(),
  derivatives: z.array(z.lazy(() => Derivative$zodSchema)).nullable().optional()
    .describe(
      "Included if 'derived=true' parameter is used. Null when no derivatives exist.",
    ),
  display_name: z.string().optional(),
  duration: z.number().nullable().optional().describe(
    "Duration in seconds for video/audio assets. Null for images.",
  ),
  etag: z.string().optional(),
  filename: z.string().optional(),
  folder: z.string().optional(),
  format: z.string().optional(),
  height: z.int().nullable().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  moderation: z.array(z.lazy(() => Moderation$zodSchema)).optional().describe(
    "Included if 'moderations=true' parameter is used.",
  ),
  moderation_kind: z.string().optional().describe(
    "The type of moderation applied to the asset.",
  ),
  moderation_status: z.string().optional().describe(
    "The current status of the moderation process for the asset.",
  ),
  pixels: z.int().nullable().optional(),
  public_id: z.string().optional(),
  related_assets: z.array(z.lazy(() => RelatedAsset$zodSchema)).nullable()
    .optional().describe(
      "Related assets linked to this resource. Null when none linked.",
    ),
  resource_subtype: z.string().nullable().optional().describe(
    "The subtype of the resource (e.g., for video). Null when not applicable.",
  ),
  resource_type: z.string().optional(),
  secure_url: z.string().optional(),
  status: z.string().optional(),
  substatus: z.string().nullable().optional().describe(
    "The substatus of the resource. Null when not set.",
  ),
  tags: z.array(z.string()).nullable().optional().describe(
    "Included if 'tags=true' parameter is used.",
  ),
  type: z.string().optional(),
  uploaded_at: z.iso.datetime({ offset: true }).optional(),
  url: z.string().optional(),
  version: z.int().optional(),
  width: z.int().nullable().optional(),
});
