/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3bcdec0b3498
 */

import * as z from "zod";
import {
  InitialBackupSummary,
  InitialBackupSummary$zodSchema,
} from "./initialbackupsummary.js";

export type InitialBackupListResponse = {
  initial_backups: Array<InitialBackupSummary>;
  next_cursor?: string | undefined;
};

export const InitialBackupListResponse$zodSchema: z.ZodType<
  InitialBackupListResponse
> = z.object({
  initial_backups: z.array(InitialBackupSummary$zodSchema).describe(
    "The list of initial backup operations.",
  ),
  next_cursor: z.string().optional().describe(
    "Cursor for the next page of results. Present only when more results are available.",
  ),
});
