/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c177b61c3c7c
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The current status of the initial backup operation.
 */
export const InitialBackupStatusEnum = {
  Pending: "pending",
  Active: "active",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * The current status of the initial backup operation.
 */
export type InitialBackupStatusEnum = ClosedEnum<
  typeof InitialBackupStatusEnum
>;

export const InitialBackupStatusEnum$zodSchema = z.enum([
  "pending",
  "active",
  "completed",
  "failed",
]).describe("The current status of the initial backup operation.");
