/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: db9fdf9579e1
 */

import * as z from "zod";

export type InitialBackupCreateRequest = { email?: string | undefined };

export const InitialBackupCreateRequest$zodSchema: z.ZodType<
  InitialBackupCreateRequest
> = z.object({
  email: z.string().optional().describe(
    "An optional email address to notify when the initial backup completes.",
  ),
});
