/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37203eb65669
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  PeopleInspectResponse,
  PeopleInspectResponse$zodSchema,
} from "./peopleinspectresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const InspectPeoplePermissionsOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type InspectPeoplePermissionsGlobals = {
  cloud_name?: string | undefined;
};

export const InspectPeoplePermissionsGlobals$zodSchema: z.ZodType<
  InspectPeoplePermissionsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type InspectPeoplePermissionsSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const InspectPeoplePermissionsSecurity$zodSchema: z.ZodType<
  InspectPeoplePermissionsSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type InspectPeoplePermissionsResponse = PeopleInspectResponse | ApiError;

export const InspectPeoplePermissionsResponse$zodSchema: z.ZodType<
  InspectPeoplePermissionsResponse
> = z.union([
  PeopleInspectResponse$zodSchema,
  ApiError$zodSchema,
]);
