/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 697be3fe78bc
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  InvalidateByUrlsResponse,
  InvalidateByUrlsResponse$zodSchema,
} from "./invalidatebyurlsresponse.js";

export type InvalidateDerivedByUrlsGlobals = {
  cloud_name?: string | undefined;
};

export const InvalidateDerivedByUrlsGlobals$zodSchema: z.ZodType<
  InvalidateDerivedByUrlsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type InvalidateDerivedByUrlsResponse =
  | ApiError
  | InvalidateByUrlsResponse;

export const InvalidateDerivedByUrlsResponse$zodSchema: z.ZodType<
  InvalidateDerivedByUrlsResponse
> = z.union([
  ApiError$zodSchema,
  InvalidateByUrlsResponse$zodSchema,
]);
