/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: da07f4b04b4b
 */

import * as z from "zod";

/**
 * The set of delivery URLs whose derived assets should be invalidated.
 */
export type InvalidateByUrlsRequest = {
  urls: Array<string>;
  skip_reporting?: boolean | undefined;
};

export const InvalidateByUrlsRequest$zodSchema: z.ZodType<
  InvalidateByUrlsRequest
> = z.object({
  skip_reporting: z.boolean().optional().describe(
    "Whether to skip recording this invalidation against the product environment usage. If false, the invalidation is counted towards usage. Default is false.",
  ),
  urls: z.array(z.string()).describe(
    "The delivery URLs whose cached derived assets should be invalidated.",
  ),
}).describe(
  "The set of delivery URLs whose derived assets should be invalidated.",
);
