/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 786274723fd0
 */

import * as z from "zod";

/**
 * The result of invalidating derived assets by delivery URLs.
 */
export type InvalidateByUrlsResponse = {
  cdn_invalidated?: boolean | undefined;
  took?: number | undefined;
  urls?: Array<string> | undefined;
  unauthorized_urls?: Array<string> | undefined;
};

export const InvalidateByUrlsResponse$zodSchema: z.ZodType<
  InvalidateByUrlsResponse
> = z.object({
  cdn_invalidated: z.boolean().optional().describe(
    "Whether the assets were invalidated directly on the CDN.",
  ),
  took: z.number().optional().describe(
    "The time the invalidation took, in seconds.",
  ),
  unauthorized_urls: z.array(z.string()).optional().describe(
    "The delivery URLs that were skipped because the caller lacked update permission.",
  ),
  urls: z.array(z.string()).optional().describe(
    "The delivery URLs that were invalidated.",
  ),
}).describe("The result of invalidating derived assets by delivery URLs.");
