/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4db2684377ee
 */

import * as z from "zod";
import {
  ResourceTypesResponse,
  ResourceTypesResponse$zodSchema,
} from "./resourcetypesresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const ListResourceTypesOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type ListResourceTypesGlobals = { cloud_name?: string | undefined };

export const ListResourceTypesGlobals$zodSchema: z.ZodType<
  ListResourceTypesGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourceTypesSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const ListResourceTypesSecurity$zodSchema: z.ZodType<
  ListResourceTypesSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type ListResourceTypesRequest = {};

export const ListResourceTypesRequest$zodSchema: z.ZodType<
  ListResourceTypesRequest
> = z.object({});

export type ListResourceTypesError = { message: string };

export const ListResourceTypesError$zodSchema: z.ZodType<
  ListResourceTypesError
> = z.object({
  message: z.string(),
});

/**
 * Authentication failed.
 */
export type ListResourceTypesResponseBody = { error: ListResourceTypesError };

export const ListResourceTypesResponseBody$zodSchema: z.ZodType<
  ListResourceTypesResponseBody
> = z.object({
  error: z.lazy(() => ListResourceTypesError$zodSchema),
}).describe("Authentication failed.");

export type ListResourceTypesResponse =
  | ListResourceTypesResponseBody
  | ResourceTypesResponse;

export const ListResourceTypesResponse$zodSchema: z.ZodType<
  ListResourceTypesResponse
> = z.union([
  z.lazy(() => ListResourceTypesResponseBody$zodSchema),
  ResourceTypesResponse$zodSchema,
]);
