/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 84760bbe9415
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FoldersListResponse,
  FoldersListResponse$zodSchema,
} from "./folderslistresponse.js";

export type ListRootFoldersGlobals = { cloud_name?: string | undefined };

export const ListRootFoldersGlobals$zodSchema: z.ZodType<
  ListRootFoldersGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListRootFoldersRequest = {};

export const ListRootFoldersRequest$zodSchema: z.ZodType<
  ListRootFoldersRequest
> = z.object({});

export type ListRootFoldersResponse = FoldersListResponse | ApiError;

export const ListRootFoldersResponse$zodSchema: z.ZodType<
  ListRootFoldersResponse
> = z.union([
  FoldersListResponse$zodSchema,
  ApiError$zodSchema,
]);
