/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { FieldsSpec, FieldsSpec$zodSchema } from "./fieldsspec.js";
import { ListResponse, ListResponse$zodSchema } from "./listresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type ListResourcesByAssetIDsGlobals = {
  cloud_name?: string | undefined;
};

export const ListResourcesByAssetIDsGlobals$zodSchema: z.ZodType<
  ListResourcesByAssetIDsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourcesByAssetIDsRequest = {
  asset_ids: Array<string>;
  resource_type?: ResourceType | undefined;
  fields?: Array<FieldsSpec> | undefined;
};

export const ListResourcesByAssetIDsRequest$zodSchema: z.ZodType<
  ListResourcesByAssetIDsRequest
> = z.object({
  asset_ids: z.array(z.string()).describe(
    "List of asset IDs to retrieve (max 100).",
  ),
  fields: z.array(FieldsSpec$zodSchema).optional(),
  resource_type: ResourceType$zodSchema.optional(),
});

export type ListResourcesByAssetIDsResponse = ApiError | ListResponse;

export const ListResourcesByAssetIDsResponse$zodSchema: z.ZodType<
  ListResourcesByAssetIDsResponse
> = z.union([
  ApiError$zodSchema,
  ListResponse$zodSchema,
]);
