/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08feb5513e5a
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { Direction, Direction$zodSchema } from "./direction.js";
import { FieldsSpec, FieldsSpec$zodSchema } from "./fieldsspec.js";
import { ListResponse, ListResponse$zodSchema } from "./listresponse.js";
import {
  ListStorageType,
  ListStorageType$zodSchema,
} from "./liststoragetype.js";

export type ListRawFilesGlobals = { cloud_name?: string | undefined };

export const ListRawFilesGlobals$zodSchema: z.ZodType<ListRawFilesGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type ListRawFilesRequest = {
  type?: ListStorageType | undefined;
  prefix?: string | undefined;
  public_ids?: Array<string> | undefined;
  tags?: boolean | undefined;
  next_cursor?: string | undefined;
  max_results?: number | undefined;
  direction?: Direction | undefined;
  start_at?: string | undefined;
  fields?: Array<FieldsSpec> | undefined;
};

export const ListRawFilesRequest$zodSchema: z.ZodType<ListRawFilesRequest> = z
  .object({
    direction: Direction$zodSchema.optional().describe("Sort direction."),
    fields: z.array(FieldsSpec$zodSchema).optional(),
    max_results: z.int().describe(
      "Maximum number of results to return (1-500).",
    ).optional(),
    next_cursor: z.string().describe("Cursor for pagination.").optional(),
    prefix: z.string().describe(
      "A public_id prefix. When specified, all assets with that prefix are returned. When using this, the `type` parameter must also be specified.",
    ).optional(),
    public_ids: z.array(z.string()).describe(
      "An array of public IDs to return.",
    ).optional(),
    start_at: z.iso.datetime({ offset: true }).describe(
      "An ISO-8601 formatted timestamp. When specified, assets created since that timestamp are returned.  Supported only if neither `prefix` nor `public_ids` were passed.",
    ).optional(),
    tags: z.boolean().describe(
      "Whether to include the list of tag names assigned to each asset. Default: false",
    ).optional(),
    type: ListStorageType$zodSchema.optional().describe(
      "The delivery type. Necessary for prefix filtering.",
    ),
  });

export type ListRawFilesResponse = ApiError | ListResponse;

export const ListRawFilesResponse$zodSchema: z.ZodType<ListRawFilesResponse> = z
  .union([
    ApiError$zodSchema,
    ListResponse$zodSchema,
  ]);
