/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4db2684377ee
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type ListResourceTypesGlobals = { cloud_name?: string | undefined };

export const ListResourceTypesGlobals$zodSchema: z.ZodType<
  ListResourceTypesGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListResourceTypesRequest = {};

export const ListResourceTypesRequest$zodSchema: z.ZodType<
  ListResourceTypesRequest
> = z.object({});

export type ListResourceTypesError = { message: string };

export const ListResourceTypesError$zodSchema: z.ZodType<
  ListResourceTypesError
> = z.object({
  message: z.string(),
});

/**
 * Authentication failed.
 */
export type ListResourceTypesUnauthorizedResponseBody = {
  error: ListResourceTypesError;
};

export const ListResourceTypesUnauthorizedResponseBody$zodSchema: z.ZodType<
  ListResourceTypesUnauthorizedResponseBody
> = z.object({
  error: z.lazy(() => ListResourceTypesError$zodSchema),
}).describe("Authentication failed.");

export const ListResourceTypesResourceType = {
  Image: "image",
  Raw: "raw",
  Video: "video",
} as const;
export type ListResourceTypesResourceType = ClosedEnum<
  typeof ListResourceTypesResourceType
>;

export const ListResourceTypesResourceType$zodSchema = z.enum([
  "image",
  "raw",
  "video",
]);

/**
 * The list of resource types.
 */
export type ListResourceTypesResponseBody = {
  resource_types?: Array<ListResourceTypesResourceType> | undefined;
};

export const ListResourceTypesResponseBody$zodSchema: z.ZodType<
  ListResourceTypesResponseBody
> = z.object({
  resource_types: z.array(ListResourceTypesResourceType$zodSchema).optional()
    .describe("The list of available resource types."),
}).describe("The list of resource types.");

export type ListResourceTypesResponse =
  | ListResourceTypesUnauthorizedResponseBody
  | ListResourceTypesResponseBody;

export const ListResourceTypesResponse$zodSchema: z.ZodType<
  ListResourceTypesResponse
> = z.union([
  z.lazy(() => ListResourceTypesUnauthorizedResponseBody$zodSchema),
  z.lazy(() => ListResourceTypesResponseBody$zodSchema),
]);
