/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d184e28eafb2
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ModerationStatusParameter = {
  Approved: "approved",
  Rejected: "rejected",
  Pending: "pending",
  Queued: "queued",
  Aborted: "aborted",
} as const;
export type ModerationStatusParameter = ClosedEnum<
  typeof ModerationStatusParameter
>;

export const ModerationStatusParameter$zodSchema = z.enum([
  "approved",
  "rejected",
  "pending",
  "queued",
  "aborted",
]);
