/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b8b780220471
 */

import * as z from "zod";

/**
 * The items to inspect for a type and the actions to check against them.
 */
export type PeopleInspectionGroup = {
  items: { [k: string]: any };
  actions: { [k: string]: any };
};

export const PeopleInspectionGroup$zodSchema: z.ZodType<PeopleInspectionGroup> =
  z.object({
    actions: z.record(z.string(), z.any()).describe(
      "A map of action names to optional action context to inspect.",
    ),
    items: z.record(z.string(), z.any()).describe(
      "A map of caller-supplied cache keys to the person identifier to inspect.",
    ),
  }).describe(
    "The items to inspect for a type and the actions to check against them.",
  );
