/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of a person.
 */
export const PersonStatus = {
  Active: "active",
  Hidden: "hidden",
} as const;
/**
 * The status of a person.
 */
export type PersonStatus = ClosedEnum<typeof PersonStatus>;

export const PersonStatus$zodSchema = z.enum([
  "active",
  "hidden",
]).describe("The status of a person.");
