/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1fe679d28276
 */

import * as z from "zod";
import { PersonDetails, PersonDetails$zodSchema } from "./persondetails.js";

export type PersonResponse = { person?: PersonDetails | undefined };

export const PersonResponse$zodSchema: z.ZodType<PersonResponse> = z.object({
  person: PersonDetails$zodSchema.optional().describe(
    "Detailed information about a recognized person.",
  ),
});
