/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9c55942ff716
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of principal.
 */
export const PrincipalType = {
  User: "user",
  Group: "group",
  ApiKey: "apiKey",
} as const;
/**
 * The type of principal.
 */
export type PrincipalType = ClosedEnum<typeof PrincipalType>;

export const PrincipalType$zodSchema = z.enum([
  "user",
  "group",
  "apiKey",
]).describe("The type of principal.");
