/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7ecf5c8c27c9
 */

import * as z from "zod";

/**
 * The asset relation request.
 */
export type RelateAssetsByPublicIdRequest = { assets_to_relate: Array<string> };

export const RelateAssetsByPublicIdRequest$zodSchema: z.ZodType<
  RelateAssetsByPublicIdRequest
> = z.object({
  assets_to_relate: z.array(z.string()).describe(
    "Relates the asset to all the other assets specified in this array of up to 10 assets, specified as resource_type/type/public_id.",
  ),
}).describe("The asset relation request.");
