/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a8a56d17bf3
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderRenameResponse,
  FolderRenameResponse$zodSchema,
} from "./folderrenameresponse.js";

export type RenameFolderOperationGlobals = { cloud_name?: string | undefined };

export const RenameFolderOperationGlobals$zodSchema: z.ZodType<
  RenameFolderOperationGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type RenameFolderOperationResponse = ApiError | FolderRenameResponse;

export const RenameFolderOperationResponse$zodSchema: z.ZodType<
  RenameFolderOperationResponse
> = z.union([
  ApiError$zodSchema,
  FolderRenameResponse$zodSchema,
]);
