/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbd9cb9b5b71
 */

import * as z from "zod";
import {
  UploadDeliveryType,
  UploadDeliveryType$zodSchema,
} from "./uploaddeliverytype.js";

/**
 * The rename request parameters.
 */
export type RenameRequest = {
  api_key?: string | undefined;
  timestamp?: number | undefined;
  signature?: string | undefined;
  from_public_id: string;
  to_public_id: string;
  type?: UploadDeliveryType | undefined;
  to_type?: UploadDeliveryType | undefined;
  overwrite?: boolean | undefined;
  invalidate?: boolean | undefined;
  context?: boolean | undefined;
  metadata?: boolean | undefined;
  notification_url?: string | undefined;
};

export const RenameRequest$zodSchema: z.ZodType<RenameRequest> = z.object({
  api_key: z.string().optional().describe(
    "The API key to use for the request. This is automatically computed by the Cloudinary's SDKs.",
  ),
  context: z.boolean().default(false).describe(
    "Whether to include contextual metadata in the response. Default is false.",
  ),
  from_public_id: z.string().describe("The public ID of the asset to rename."),
  invalidate: z.boolean().default(false).describe(
    "Whether to invalidate CDN cache copies of the renamed asset. Default is false.",
  ),
  metadata: z.boolean().default(false).describe(
    "Whether to include structured metadata in the response. Default is false.",
  ),
  notification_url: z.string().optional().describe(
    "URL to notify when the operation is complete.",
  ),
  overwrite: z.boolean().default(false).describe(
    "Whether to overwrite the target asset if it already exists. Default is false.",
  ),
  signature: z.string().optional().describe(
    "(Required for signed REST API calls) Used to authenticate the request and based on the parameters you use in the request. When using the Cloudinary SDKs for signed requests, the signature is automatically generated and added to the request. If you manually generate your own signed POST request, you need to manually generate the signature parameter and add it to the request together with the api_key and timestamp parameters.\n",
  ),
  timestamp: z.int().optional().describe(
    "The timestamp to use for the request in unix time. This is automatically computed by the Cloudinary's SDKs.",
  ),
  to_public_id: z.string().describe("The new public ID for the asset."),
  to_type: UploadDeliveryType$zodSchema.optional().describe(
    "The target delivery type for the renamed asset. If omitted, the delivery type remains unchanged.",
  ),
  type: UploadDeliveryType$zodSchema.optional().describe(
    "The current delivery type of the asset.",
  ),
}).describe("The rename request parameters.");
