/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a8a56d17bf3
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FolderRenameResponse,
  FolderRenameResponse$zodSchema,
} from "./folderrenameresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const RenameFolderOperationOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type RenameFolderOperationGlobals = { cloud_name?: string | undefined };

export const RenameFolderOperationGlobals$zodSchema: z.ZodType<
  RenameFolderOperationGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type RenameFolderOperationSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const RenameFolderOperationSecurity$zodSchema: z.ZodType<
  RenameFolderOperationSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type RenameFolderOperationResponse = ApiError | FolderRenameResponse;

export const RenameFolderOperationResponse$zodSchema: z.ZodType<
  RenameFolderOperationResponse
> = z.union([
  ApiError$zodSchema,
  FolderRenameResponse$zodSchema,
]);
