/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 189398e65a00
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { RenameRequest, RenameRequest$zodSchema } from "./renamerequest.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export type RenameAssetGlobals = { cloud_name?: string | undefined };

export const RenameAssetGlobals$zodSchema: z.ZodType<RenameAssetGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type RenameAssetRequest = {
  resource_type: ResourceType;
  rename_request: RenameRequest;
};

export const RenameAssetRequest$zodSchema: z.ZodType<RenameAssetRequest> = z
  .object({
    rename_request: RenameRequest$zodSchema.describe(
      "The rename request parameters.",
    ),
    resource_type: ResourceType$zodSchema.describe(
      "The type of resource (image, video, or raw).",
    ),
  });

export type RenameAssetResponse = ApiError | UploadResponse;

export const RenameAssetResponse$zodSchema: z.ZodType<RenameAssetResponse> = z
  .union([
    ApiError$zodSchema,
    UploadResponse$zodSchema,
  ]);
