/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b4e8441d1842
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ResourceTypesResponseResourceType = {
  Image: "image",
  Raw: "raw",
  Video: "video",
} as const;
export type ResourceTypesResponseResourceType = ClosedEnum<
  typeof ResourceTypesResponseResourceType
>;

export const ResourceTypesResponseResourceType$zodSchema = z.enum([
  "image",
  "raw",
  "video",
]);

export type ResourceTypesResponse = {
  resource_types?: Array<ResourceTypesResponseResourceType> | undefined;
};

export const ResourceTypesResponse$zodSchema: z.ZodType<ResourceTypesResponse> =
  z.object({
    resource_types: z.array(ResourceTypesResponseResourceType$zodSchema)
      .optional().describe("The list of available resource types."),
  });
