/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aba3f59bb468
 */

import * as z from "zod";
import {
  ResourceInternalResponse,
  ResourceInternalResponse$zodSchema,
} from "./resourceinternalresponse.js";

/**
 * A page of assets contained in a folder, with pagination metadata.
 */
export type ResourcesByContainerIdResponse = {
  resources: Array<ResourceInternalResponse>;
  total_count?: number | undefined;
  next_cursor?: string | undefined;
};

export const ResourcesByContainerIdResponse$zodSchema: z.ZodType<
  ResourcesByContainerIdResponse
> = z.object({
  next_cursor: z.string().optional().describe(
    "A cursor for retrieving the next page of results, when more results are available.",
  ),
  resources: z.array(ResourceInternalResponse$zodSchema).describe(
    "The assets contained in the folder.",
  ),
  total_count: z.int().optional().describe(
    "The total number of assets in the folder.",
  ),
}).describe(
  "A page of assets contained in a folder, with pagination metadata.",
);
