/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2f9165e777b1
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of the asset (image, video, or raw).
 */
export const ResourceGetByBodyRequestResourceType = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * The type of the asset (image, video, or raw).
 */
export type ResourceGetByBodyRequestResourceType = ClosedEnum<
  typeof ResourceGetByBodyRequestResourceType
>;

export const ResourceGetByBodyRequestResourceType$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe("The type of the asset (image, video, or raw).");

/**
 * The delivery type of the asset.
 */
export const ResourceGetByBodyRequestKind = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The delivery type of the asset.
 */
export type ResourceGetByBodyRequestKind = ClosedEnum<
  typeof ResourceGetByBodyRequestKind
>;

export const ResourceGetByBodyRequestKind$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
]).describe("The delivery type of the asset.");

/**
 * The identifying attributes of the asset to retrieve.
 */
export type ResourceGetByBodyRequest = {
  public_id: string;
  resource_type: ResourceGetByBodyRequestResourceType;
  kind: ResourceGetByBodyRequestKind;
  with_elastic?: boolean | undefined;
  derived?: boolean | undefined;
  versions?: boolean | undefined;
  AdditionalProperties?: { [k: string]: any };
};

export const ResourceGetByBodyRequest$zodSchema: z.ZodType<
  ResourceGetByBodyRequest
> = collectExtraKeys$(
  z.object({
    derived: z.boolean().optional().describe(
      "Whether to include the derived assets of this asset in the response. Default is true.",
    ),
    kind: ResourceGetByBodyRequestKind$zodSchema.describe(
      "The delivery type of the asset.",
    ),
    public_id: z.string().describe("The public ID of the asset to retrieve."),
    resource_type: ResourceGetByBodyRequestResourceType$zodSchema.describe(
      "The type of the asset (image, video, or raw).",
    ),
    versions: z.boolean().optional().describe(
      "Whether to include the backup versions of this asset in the response. Default is false.",
    ),
    with_elastic: z.boolean().optional().describe(
      "Whether to source the asset details from the search index. If false, the details are read directly from the canonical store. Default is true.",
    ),
  }).describe("The identifying attributes of the asset to retrieve.").catchall(
    z.any(),
  ),
  "AdditionalProperties",
  true,
);

export const ResourceGetByBodyRequest$zodSchemaOutbound: z.ZodType<any> = z
  .object({
    AdditionalProperties: z.record(z.string(), z.any()).optional(),
    derived: z.boolean().optional(),
    kind: ResourceGetByBodyRequestKind$zodSchema,
    public_id: z.string(),
    resource_type: ResourceGetByBodyRequestResourceType$zodSchema,
    versions: z.boolean().optional(),
    with_elastic: z.boolean().optional(),
  }).describe("The identifying attributes of the asset to retrieve.").transform(
    (v) => {
      const { AdditionalProperties, ...rest } = v;
      return {
        ...rest,
        ...AdditionalProperties,
      };
    },
  );
