/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";

/**
 * The moderation status of the resource.
 */
export const ModerationStatus = {
  Approved: "approved",
  Rejected: "rejected",
} as const;
/**
 * The moderation status of the resource.
 */
export type ModerationStatus = ClosedEnum<typeof ModerationStatus>;

export const ModerationStatus$zodSchema = z.enum([
  "approved",
  "rejected",
]).describe("The moderation status of the resource.");

export type ResourceUpdateRequest = {
  display_name?: string | undefined;
  unique_display_name?: boolean | undefined;
  asset_folder?: string | undefined;
  tags?: string | undefined;
  context?: string | undefined;
  metadata?: string | undefined;
  clear_invalid?: boolean | undefined;
  face_coordinates?: string | undefined;
  custom_coordinates?: string | undefined;
  regions?: string | undefined;
  quality_override?: string | undefined;
  moderation_status?: ModerationStatus | undefined;
  auto_tagging?: number | undefined;
  detection?: string | undefined;
  ocr?: string | undefined;
  raw_convert?: string | undefined;
  categorization?: string | undefined;
  visual_search?: boolean | undefined;
  background_removal?: string | undefined;
  access_control?: Array<AccessControlItem> | undefined;
};

export const ResourceUpdateRequest$zodSchema: z.ZodType<ResourceUpdateRequest> =
  z.object({
    access_control: z.array(AccessControlItem$zodSchema).optional(),
    asset_folder: z.string().optional(),
    auto_tagging: z.number().optional(),
    background_removal: z.string().optional(),
    categorization: z.string().optional(),
    clear_invalid: z.boolean().default(false),
    context: z.string().optional(),
    custom_coordinates: z.string().optional(),
    detection: z.string().optional(),
    display_name: z.string().optional(),
    face_coordinates: z.string().optional(),
    metadata: z.string().optional(),
    moderation_status: ModerationStatus$zodSchema.optional(),
    ocr: z.string().optional(),
    quality_override: z.string().optional(),
    raw_convert: z.string().optional(),
    regions: z.string().optional(),
    tags: z.string().optional(),
    unique_display_name: z.boolean().default(false),
    visual_search: z.boolean().optional(),
  });
