/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3c17bbd5de7c
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import {
  AdminContextOperation,
  AdminContextOperation$zodSchema,
} from "./admincontextoperation.js";

/**
 * The type of the asset (image, video, or raw).
 */
export const ResourceUpdateByBodyRequestResourceType = {
  Image: "image",
  Video: "video",
  Raw: "raw",
} as const;
/**
 * The type of the asset (image, video, or raw).
 */
export type ResourceUpdateByBodyRequestResourceType = ClosedEnum<
  typeof ResourceUpdateByBodyRequestResourceType
>;

export const ResourceUpdateByBodyRequestResourceType$zodSchema = z.enum([
  "image",
  "video",
  "raw",
]).describe("The type of the asset (image, video, or raw).");

/**
 * The delivery type of the asset.
 */
export const ResourceUpdateByBodyRequestKind = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The delivery type of the asset.
 */
export type ResourceUpdateByBodyRequestKind = ClosedEnum<
  typeof ResourceUpdateByBodyRequestKind
>;

export const ResourceUpdateByBodyRequestKind$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
]).describe("The delivery type of the asset.");

/**
 * The moderation status to set on the asset.
 */
export const ResourceUpdateByBodyRequestModerationStatus = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
} as const;
/**
 * The moderation status to set on the asset.
 */
export type ResourceUpdateByBodyRequestModerationStatus = ClosedEnum<
  typeof ResourceUpdateByBodyRequestModerationStatus
>;

export const ResourceUpdateByBodyRequestModerationStatus$zodSchema = z.enum([
  "pending",
  "approved",
  "rejected",
]).describe("The moderation status to set on the asset.");

/**
 * The asset identifiers plus the attributes to update. The identifying fields (public_id,
 *
 * @remarks
 * resource_type, kind) are required; the remaining update fields are optional. Additional
 * fields accepted by the asset update API are permitted.
 */
export type ResourceUpdateByBodyRequest = {
  public_id: string;
  resource_type: ResourceUpdateByBodyRequestResourceType;
  kind: ResourceUpdateByBodyRequestKind;
  tags?: Array<string> | undefined;
  context?: { [k: string]: any } | undefined;
  metadata?: { [k: string]: any } | undefined;
  asset_folder?: string | undefined;
  display_name?: string | undefined;
  moderation_status?: ResourceUpdateByBodyRequestModerationStatus | undefined;
  admin_context?: Array<AdminContextOperation> | undefined;
  response_type?: string | undefined;
  skip_permission_check?: boolean | undefined;
  AdditionalProperties?: { [k: string]: any };
};

export const ResourceUpdateByBodyRequest$zodSchema: z.ZodType<
  ResourceUpdateByBodyRequest
> = collectExtraKeys$(
  z.object({
    admin_context: z.array(AdminContextOperation$zodSchema).optional().describe(
      "Internal-only contextual metadata operations applied with add/remove semantics. Each\nentry names a context key, the value(s) to apply, the value type, and the operation.\n",
    ),
    asset_folder: z.string().optional().describe(
      "The asset folder to move the asset into.",
    ),
    context: z.record(z.string(), z.any()).optional().describe(
      "The key-value pairs of contextual metadata to assign to the asset.",
    ),
    display_name: z.string().optional().describe(
      "The display name to assign to the asset.",
    ),
    kind: ResourceUpdateByBodyRequestKind$zodSchema.describe(
      "The delivery type of the asset.",
    ),
    metadata: z.record(z.string(), z.any()).optional().describe(
      "The structured metadata field values to assign to the asset.",
    ),
    moderation_status: ResourceUpdateByBodyRequestModerationStatus$zodSchema
      .optional().describe("The moderation status to set on the asset."),
    public_id: z.string().describe("The public ID of the asset to update."),
    resource_type: ResourceUpdateByBodyRequestResourceType$zodSchema.describe(
      "The type of the asset (image, video, or raw).",
    ),
    response_type: z.string().optional().describe(
      "The shape of the asset representation to return (for example, \"public\").",
    ),
    skip_permission_check: z.boolean().optional().describe(
      "Whether to skip permission enforcement for the update. Internal use only. Default is false.",
    ),
    tags: z.array(z.string()).optional().describe(
      "The list of tags to assign to the asset, replacing any existing tags.",
    ),
  }).describe(
    "The asset identifiers plus the attributes to update. The identifying fields (public_id,\nresource_type, kind) are required; the remaining update fields are optional. Additional\nfields accepted by the asset update API are permitted.\n",
  ).catchall(z.any()),
  "AdditionalProperties",
  true,
);

export const ResourceUpdateByBodyRequest$zodSchemaOutbound: z.ZodType<any> = z
  .object({
    AdditionalProperties: z.record(z.string(), z.any()).optional(),
    admin_context: z.array(AdminContextOperation$zodSchema).optional(),
    asset_folder: z.string().optional(),
    context: z.record(z.string(), z.any()).optional(),
    display_name: z.string().optional(),
    kind: ResourceUpdateByBodyRequestKind$zodSchema,
    metadata: z.record(z.string(), z.any()).optional(),
    moderation_status: ResourceUpdateByBodyRequestModerationStatus$zodSchema
      .optional(),
    public_id: z.string(),
    resource_type: ResourceUpdateByBodyRequestResourceType$zodSchema,
    response_type: z.string().optional(),
    skip_permission_check: z.boolean().optional(),
    tags: z.array(z.string()).optional(),
  }).describe(
    "The asset identifiers plus the attributes to update. The identifying fields (public_id,\nresource_type, kind) are required; the remaining update fields are optional. Additional\nfields accepted by the asset update API are permitted.\n",
  ).transform((v) => {
    const { AdditionalProperties, ...rest } = v;
    return {
      ...rest,
      ...AdditionalProperties,
    };
  });
