/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  FoldersSearchResponse,
  FoldersSearchResponse$zodSchema,
} from "./folderssearchresponse.js";

export type SearchFoldersPostGlobals = { cloud_name?: string | undefined };

export const SearchFoldersPostGlobals$zodSchema: z.ZodType<
  SearchFoldersPostGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type SearchFoldersPostRequest = {
  expression?: string | undefined;
  sort_by?: Array<string> | undefined;
  max_results?: number | undefined;
  next_cursor?: string | undefined;
};

export const SearchFoldersPostRequest$zodSchema: z.ZodType<
  SearchFoldersPostRequest
> = z.object({
  expression: z.string().optional(),
  max_results: z.int().default(50),
  next_cursor: z.string().optional(),
  sort_by: z.array(z.string()).optional(),
});

export type SearchFoldersPostResponse = FoldersSearchResponse | ApiError;

export const SearchFoldersPostResponse$zodSchema: z.ZodType<
  SearchFoldersPostResponse
> = z.union([
  FoldersSearchResponse$zodSchema,
  ApiError$zodSchema,
]);
