/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d2bebd37bf29
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SearchSortPair = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SearchSortPair = ClosedEnum<typeof SearchSortPair>;

export const SearchSortPair$zodSchema = z.enum([
  "asc",
  "desc",
]);
