/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 19a313de27e8
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";
import { SearchResponse, SearchResponse$zodSchema } from "./searchresponse.js";

export const SearchAssetsOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type SearchAssetsGlobals = { cloud_name?: string | undefined };

export const SearchAssetsGlobals$zodSchema: z.ZodType<SearchAssetsGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type SearchAssetsSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const SearchAssetsSecurity$zodSchema: z.ZodType<SearchAssetsSecurity> = z
  .object({
    cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
    oauth2: z.string().describe(
      "OAuth2 Authorization Code flow for user authentication",
    ).optional(),
  });

export type SearchAssetsResponse = ApiError | SearchResponse;

export const SearchAssetsResponse$zodSchema: z.ZodType<SearchAssetsResponse> = z
  .union([
    ApiError$zodSchema,
    SearchResponse$zodSchema,
  ]);
