/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The storage type of the resource.
 */
export const StorageTypeParameter = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The storage type of the resource.
 */
export type StorageTypeParameter = ClosedEnum<typeof StorageTypeParameter>;

export const StorageTypeParameter$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
]).describe("The storage type of the resource.");
