/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a49c6a61da8e
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";
import { TextRequest, TextRequest$zodSchema } from "./textrequest.js";
import { TextResponse, TextResponse$zodSchema } from "./textresponse.js";

export const TextOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type TextGlobals = { cloud_name?: string | undefined };

export const TextGlobals$zodSchema: z.ZodType<TextGlobals> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type TextSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const TextSecurity$zodSchema: z.ZodType<TextSecurity> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

/**
 * The type of resource to create. Must be "image" for text generation.
 */
export const TextResourceType = {
  Image: "image",
} as const;
/**
 * The type of resource to create. Must be "image" for text generation.
 */
export type TextResourceType = ClosedEnum<typeof TextResourceType>;

export const TextResourceType$zodSchema = z.enum([
  "image",
]).describe(
  "The type of resource to create. Must be \"image\" for text generation.",
);

export type TextRequestRequest = {
  resource_type: TextResourceType;
  text_request: TextRequest;
};

export const TextRequestRequest$zodSchema: z.ZodType<TextRequestRequest> = z
  .object({
    resource_type: TextResourceType$zodSchema.describe(
      "The type of resource to create. Must be \"image\" for text generation.",
    ),
    text_request: TextRequest$zodSchema.describe(
      "The text content and styling parameters for image generation.",
    ),
  });

export type TextResponseResponse = ApiError | TextResponse;

export const TextResponseResponse$zodSchema: z.ZodType<TextResponseResponse> = z
  .union([
    ApiError$zodSchema,
    TextResponse$zodSchema,
  ]);
