/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 17b93f19a464
 */

import * as z from "zod";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";

export type Region = {};

export const Region$zodSchema: z.ZodType<Region> = z.object({});

/**
 * Moderation information for the asset.
 */
export type TextResponseModeration = {};

export const TextResponseModeration$zodSchema: z.ZodType<
  TextResponseModeration
> = z.object({}).describe("Moderation information for the asset.");

/**
 * Additional information about the asset.
 */
export type TextResponseInfo = {};

export const TextResponseInfo$zodSchema: z.ZodType<TextResponseInfo> = z.object(
  {},
).describe("Additional information about the asset.");

export type TextResponse = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  version?: number | undefined;
  version_id?: string | undefined;
  signature?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  format?: string | undefined;
  resource_type?: string | undefined;
  created_at?: string | undefined;
  tags?: Array<string> | null | undefined;
  pages?: number | undefined;
  bytes?: number | undefined;
  type?: string | undefined;
  etag?: string | undefined;
  placeholder?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  display_name?: string | undefined;
  access_control?: Array<AccessControlItem> | undefined;
  regions?: Array<Region> | undefined;
  moderation?: TextResponseModeration | undefined;
  info?: TextResponseInfo | undefined;
};

export const TextResponse$zodSchema: z.ZodType<TextResponse> = z.object({
  access_control: z.array(AccessControlItem$zodSchema).optional().describe(
    "Restricts access to the asset by specifying one or more access types.\nThe asset is restricted unless at least one listed access type is valid.\n",
  ),
  asset_id: z.string().optional().describe(
    "A 32-character hexadecimal asset ID.",
  ),
  bytes: z.int().optional().describe("Size of the asset in bytes."),
  created_at: z.iso.datetime({ offset: true }).optional().describe(
    "The creation timestamp.",
  ),
  display_name: z.string().optional().describe(
    "The display name of the asset.",
  ),
  etag: z.string().optional().describe("The ETag of the asset."),
  format: z.string().optional().describe("The format of the generated image."),
  height: z.int().optional().describe(
    "The height of the generated image in pixels.",
  ),
  info: z.lazy(() => TextResponseInfo$zodSchema).optional().describe(
    "Additional information about the asset.",
  ),
  moderation: z.lazy(() => TextResponseModeration$zodSchema).optional()
    .describe("Moderation information for the asset."),
  pages: z.int().optional().describe("Number of pages in the asset."),
  placeholder: z.boolean().optional().describe(
    "Whether the asset is a placeholder.",
  ),
  public_id: z.string().optional().describe(
    "The public identifier of the asset.",
  ),
  regions: z.array(z.lazy(() => Region$zodSchema)).optional().describe(
    "Region information for the asset.",
  ),
  resource_type: z.string().optional().describe(
    "The type of resource (image).",
  ),
  secure_url: z.string().optional().describe(
    "The HTTPS URL for accessing the asset.",
  ),
  signature: z.string().optional().describe("The signature for the asset."),
  tags: z.array(z.string()).nullable().optional().describe(
    "Tag names assigned to the asset.",
  ),
  type: z.string().optional().describe("The storage type of the asset."),
  url: z.string().optional().describe("The HTTP URL for accessing the asset."),
  version: z.int().optional().describe("The version number of the asset."),
  version_id: z.string().optional().describe(
    "Hexadecimal version ID; length is a positive multiple of 32 (typically 32 or 64).",
  ),
  width: z.int().optional().describe(
    "The width of the generated image in pixels.",
  ),
});
