/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5606c8e3b931
 */

import * as z from "zod";

/**
 * The thumbnail image for a person.
 */
export type Thumbnail = {
  asset_id?: string | undefined;
  bounding_box?: Array<number> | undefined;
  url?: string | undefined;
  resource_type?: string | undefined;
  type?: string | undefined;
  public_id?: string | undefined;
  version?: number | undefined;
};

export const Thumbnail$zodSchema: z.ZodType<Thumbnail> = z.object({
  asset_id: z.string().optional().describe(
    "The external ID of the asset used for the thumbnail.",
  ),
  bounding_box: z.array(z.int()).optional().describe(
    "The bounding box coordinates [x, y, width, height] of the face in the asset.",
  ),
  public_id: z.string().optional().describe("The public ID of the asset."),
  resource_type: z.string().optional().describe(
    "The resource type of the asset.",
  ),
  type: z.string().optional().describe("The kind/type of the asset."),
  url: z.string().optional().describe("The secure URL of the thumbnail asset."),
  version: z.int().optional().describe("The version number of the asset."),
}).describe("The thumbnail image for a person.");
