/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a76fc360f242
 */

import * as z from "zod";

/**
 * The asset unrelation request.
 */
export type UnrelateAssetsByPublicIdRequest = {
  assets_to_unrelate: Array<string>;
};

export const UnrelateAssetsByPublicIdRequest$zodSchema: z.ZodType<
  UnrelateAssetsByPublicIdRequest
> = z.object({
  assets_to_unrelate: z.array(z.string()).describe(
    "Unrelates the asset from all the assets specified in this array of assets, specified as resource_type/type/public_id.",
  ),
}).describe("The asset unrelation request.");
