/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: acabe845bac8
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  PublicIdsResponse,
  PublicIdsResponse$zodSchema,
} from "./publicidsresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  TagsUpdateRequest,
  TagsUpdateRequest$zodSchema,
} from "./tagsupdaterequest.js";

export type UpdateAssetsTagsGlobals = { cloud_name?: string | undefined };

export const UpdateAssetsTagsGlobals$zodSchema: z.ZodType<
  UpdateAssetsTagsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateAssetsTagsRequest = {
  resource_type: ResourceType;
  tags_update_request: TagsUpdateRequest;
};

export const UpdateAssetsTagsRequest$zodSchema: z.ZodType<
  UpdateAssetsTagsRequest
> = z.object({
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  tags_update_request: TagsUpdateRequest$zodSchema.describe(
    "The tag command, the tags to apply, and the assets to apply them to.",
  ),
});

export type UpdateAssetsTagsResponse = ApiError | PublicIdsResponse;

export const UpdateAssetsTagsResponse$zodSchema: z.ZodType<
  UpdateAssetsTagsResponse
> = z.union([
  ApiError$zodSchema,
  PublicIdsResponse$zodSchema,
]);
