/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 999f90d330ea
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ResourceInternalResponse,
  ResourceInternalResponse$zodSchema,
} from "./resourceinternalresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";

export const UpdateResourceByBodyOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type UpdateResourceByBodyGlobals = { cloud_name?: string | undefined };

export const UpdateResourceByBodyGlobals$zodSchema: z.ZodType<
  UpdateResourceByBodyGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByBodySecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const UpdateResourceByBodySecurity$zodSchema: z.ZodType<
  UpdateResourceByBodySecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

export type UpdateResourceByBodyResponse = ApiError | ResourceInternalResponse;

export const UpdateResourceByBodyResponse$zodSchema: z.ZodType<
  UpdateResourceByBodyResponse
> = z.union([
  ApiError$zodSchema,
  ResourceInternalResponse$zodSchema,
]);
