/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c10dd50c3c15
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type UpdateFolderGlobals = { cloud_name?: string | undefined };

export const UpdateFolderGlobals$zodSchema: z.ZodType<UpdateFolderGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type UpdateFolderRequestBody = { to_folder: string };

export const UpdateFolderRequestBody$zodSchema: z.ZodType<
  UpdateFolderRequestBody
> = z.object({
  to_folder: z.string().describe("The new path for the folder."),
});

export type UpdateFolderRequest = {
  folder: string;
  RequestBody: UpdateFolderRequestBody;
};

export const UpdateFolderRequest$zodSchema: z.ZodType<UpdateFolderRequest> = z
  .object({
    RequestBody: z.lazy(() => UpdateFolderRequestBody$zodSchema),
    folder: z.string(),
  });

export type From = { name: string; path: string };

export const From$zodSchema: z.ZodType<From> = z.object({
  name: z.string().describe("The name of the source folder."),
  path: z.string().describe("The full path of the source folder."),
});

export type To = { name: string; path: string };

export const To$zodSchema: z.ZodType<To> = z.object({
  name: z.string().describe("The name of the target folder."),
  path: z.string().describe("The full path of the target folder."),
});

/**
 * Folder renamed successfully
 */
export type UpdateFolderResponseBody = { from: From; to: To };

export const UpdateFolderResponseBody$zodSchema: z.ZodType<
  UpdateFolderResponseBody
> = z.object({
  from: z.lazy(() => From$zodSchema),
  to: z.lazy(() => To$zodSchema),
}).describe("Folder renamed successfully");

export type UpdateFolderResponse = UpdateFolderResponseBody | ApiError;

export const UpdateFolderResponse$zodSchema: z.ZodType<UpdateFolderResponse> = z
  .union([
    z.lazy(() => UpdateFolderResponseBody$zodSchema),
    ApiError$zodSchema,
  ]);
