/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9f52bba90243
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ContextUpdateRequest,
  ContextUpdateRequest$zodSchema,
} from "./contextupdaterequest.js";
import {
  PublicIdsResponse,
  PublicIdsResponse$zodSchema,
} from "./publicidsresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type UpdateAssetsContextGlobals = { cloud_name?: string | undefined };

export const UpdateAssetsContextGlobals$zodSchema: z.ZodType<
  UpdateAssetsContextGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateAssetsContextRequest = {
  resource_type: ResourceType;
  context_update_request: ContextUpdateRequest;
};

export const UpdateAssetsContextRequest$zodSchema: z.ZodType<
  UpdateAssetsContextRequest
> = z.object({
  context_update_request: ContextUpdateRequest$zodSchema.describe(
    "The context command, the metadata to apply, and the assets to apply it to.",
  ),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
});

export type UpdateAssetsContextResponse = ApiError | PublicIdsResponse;

export const UpdateAssetsContextResponse$zodSchema: z.ZodType<
  UpdateAssetsContextResponse
> = z.union([
  ApiError$zodSchema,
  PublicIdsResponse$zodSchema,
]);
