/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 999f90d330ea
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  ResourceInternalResponse,
  ResourceInternalResponse$zodSchema,
} from "./resourceinternalresponse.js";

export type UpdateResourceByBodyGlobals = { cloud_name?: string | undefined };

export const UpdateResourceByBodyGlobals$zodSchema: z.ZodType<
  UpdateResourceByBodyGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByBodyResponse = ApiError | ResourceInternalResponse;

export const UpdateResourceByBodyResponse$zodSchema: z.ZodType<
  UpdateResourceByBodyResponse
> = z.union([
  ApiError$zodSchema,
  ResourceInternalResponse$zodSchema,
]);
