/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { PersonStatus, PersonStatus$zodSchema } from "./personstatus.js";

export type UpdatePersonGlobals = { cloud_name?: string | undefined };

export const UpdatePersonGlobals$zodSchema: z.ZodType<UpdatePersonGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type UpdatePersonRequestBody = {
  name?: string | undefined;
  status?: PersonStatus | undefined;
  thumbnail_asset_id?: string | undefined;
};

export const UpdatePersonRequestBody$zodSchema: z.ZodType<
  UpdatePersonRequestBody
> = z.object({
  name: z.string().optional(),
  status: PersonStatus$zodSchema.optional(),
  thumbnail_asset_id: z.string().optional(),
});

export type UpdatePersonRequest = {
  person_id: string;
  RequestBody: UpdatePersonRequestBody;
};

export const UpdatePersonRequest$zodSchema: z.ZodType<UpdatePersonRequest> = z
  .object({
    RequestBody: z.lazy(() => UpdatePersonRequestBody$zodSchema),
    person_id: z.string().describe("The unique identifier of the person."),
  });

/**
 * Person updated successfully
 */
export type UpdatePersonResponseBody = {
  person_id?: string | undefined;
  name?: string | undefined;
  status?: PersonStatus | undefined;
};

export const UpdatePersonResponseBody$zodSchema: z.ZodType<
  UpdatePersonResponseBody
> = z.object({
  name: z.string().optional(),
  person_id: z.string().optional(),
  status: PersonStatus$zodSchema.optional(),
}).describe("Person updated successfully");

export type UpdatePersonResponse = ApiError | UpdatePersonResponseBody;

export const UpdatePersonResponse$zodSchema: z.ZodType<UpdatePersonResponse> = z
  .union([
    ApiError$zodSchema,
    z.lazy(() => UpdatePersonResponseBody$zodSchema),
  ]);
