/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5ddf6ef3582c
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  UpdatePersonRequest,
  UpdatePersonRequest$zodSchema,
} from "./updatepersonrequest.js";
import {
  UpdatePersonResponse,
  UpdatePersonResponse$zodSchema,
} from "./updatepersonresponse.js";

export type UpdatePersonGlobals = { cloud_name?: string | undefined };

export const UpdatePersonGlobals$zodSchema: z.ZodType<UpdatePersonGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type UpdatePersonRequestRequest = {
  person_id: string;
  update_person_request: UpdatePersonRequest;
};

export const UpdatePersonRequestRequest$zodSchema: z.ZodType<
  UpdatePersonRequestRequest
> = z.object({
  person_id: z.string().describe("The unique identifier of the person."),
  update_person_request: UpdatePersonRequest$zodSchema.describe(
    "The updated person attributes.",
  ),
});

export type UpdatePersonResponseResponse = ApiError | UpdatePersonResponse;

export const UpdatePersonResponseResponse$zodSchema: z.ZodType<
  UpdatePersonResponseResponse
> = z.union([
  ApiError$zodSchema,
  UpdatePersonResponse$zodSchema,
]);
