/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba93ee3907fd
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MetadataUpdateRequest,
  MetadataUpdateRequest$zodSchema,
} from "./metadataupdaterequest.js";
import {
  PublicIdsResponse,
  PublicIdsResponse$zodSchema,
} from "./publicidsresponse.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";

export type UpdateAssetsMetadataGlobals = { cloud_name?: string | undefined };

export const UpdateAssetsMetadataGlobals$zodSchema: z.ZodType<
  UpdateAssetsMetadataGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateAssetsMetadataRequest = {
  resource_type: ResourceType;
  metadata_update_request: MetadataUpdateRequest;
};

export const UpdateAssetsMetadataRequest$zodSchema: z.ZodType<
  UpdateAssetsMetadataRequest
> = z.object({
  metadata_update_request: MetadataUpdateRequest$zodSchema.describe(
    "The structured metadata values to assign and the assets to assign them to.",
  ),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
});

export type UpdateAssetsMetadataResponse = ApiError | PublicIdsResponse;

export const UpdateAssetsMetadataResponse$zodSchema: z.ZodType<
  UpdateAssetsMetadataResponse
> = z.union([
  ApiError$zodSchema,
  PublicIdsResponse$zodSchema,
]);
