/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3bb8de4a09c1
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { Info, Info$zodSchema } from "./info.js";
import { ResourceType, ResourceType$zodSchema } from "./resourcetype.js";
import {
  ResourceUpdateRequest,
  ResourceUpdateRequest$zodSchema,
} from "./resourceupdaterequest.js";

export type UpdateResourceByPublicIdGlobals = {
  cloud_name?: string | undefined;
};

export const UpdateResourceByPublicIdGlobals$zodSchema: z.ZodType<
  UpdateResourceByPublicIdGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateResourceByPublicIdRequest = {
  resource_type: ResourceType;
  type: string;
  public_id: string;
  ResourceUpdateRequest: ResourceUpdateRequest;
};

export const UpdateResourceByPublicIdRequest$zodSchema: z.ZodType<
  UpdateResourceByPublicIdRequest
> = z.object({
  ResourceUpdateRequest: ResourceUpdateRequest$zodSchema.describe(
    "The asset attributes to update.",
  ),
  public_id: z.string().describe("The public ID of the asset."),
  resource_type: ResourceType$zodSchema.describe(
    "The type of resource (image, video, or raw).",
  ),
  type: z.string().describe("The delivery type of the asset."),
});

export type UpdateResourceByPublicIdResponse = ApiError | Info;

export const UpdateResourceByPublicIdResponse$zodSchema: z.ZodType<
  UpdateResourceByPublicIdResponse
> = z.union([
  ApiError$zodSchema,
  Info$zodSchema,
]);
