/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e409cc80108
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AsyncUploadResponse,
  AsyncUploadResponse$zodSchema,
} from "./asyncuploadresponse.js";
import {
  NonFinalChunkUploadResponse,
  NonFinalChunkUploadResponse$zodSchema,
} from "./nonfinalchunkuploadresponse.js";
import { UploadRequest, UploadRequest$zodSchema } from "./uploadrequest.js";
import {
  UploadResourceType,
  UploadResourceType$zodSchema,
} from "./uploadresourcetype.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export type UploadChunkGlobals = { cloud_name?: string | undefined };

export const UploadChunkGlobals$zodSchema: z.ZodType<UploadChunkGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

export type UploadChunkRequest = {
  resource_type?: UploadResourceType | undefined;
  contentRange?: string | undefined;
  xUniqueUploadId: string;
  xUploadPartNumber?: number | undefined;
  xUploadTotalParts?: number | undefined;
  upload_request: UploadRequest;
};

export const UploadChunkRequest$zodSchema: z.ZodType<UploadChunkRequest> = z
  .object({
    contentRange: z.string().describe(
      "The range of bytes being uploaded in the current chunk, in the format \"bytes start-end/total\".\nFor example, \"bytes 0-999999/3000000\" indicates the first 1MB chunk of a 3MB file. Required for the\ndefault uniform-size chunked upload flow. In explicit-order mode (`X-Upload-Part-Number`), this\nheader remains optional; clients do not have to send `Content-Range`, `X-Upload-Part-Number`, and\n`X-Upload-Total-Parts` together on every request—`X-Upload-Total-Parts` may be omitted on some chunks\nsubject to the rules documented on that header.\n",
    ).optional(),
    resource_type: UploadResourceType$zodSchema.default("auto").describe(
      "The type of resource (image, video, raw, or auto).",
    ),
    upload_request: UploadRequest$zodSchema.describe(
      "The file to upload and associated parameters.",
    ),
    xUniqueUploadId: z.string().describe(
      "A unique identifier for the upload. Must be the same for all chunks of the same file.",
    ),
    xUploadPartNumber: z.int().describe(
      "The 1-based part number for this chunk when uploading parts of uneven size with explicit\nclient-supplied order. Requires `X-Unique-Upload-Id`. When present, activates explicit-order mode\nand `Content-Range` is optional. Parts must use contiguous indices `1`…`N`, where `N` is the session\ntotal. If `X-Upload-Total-Parts` is omitted on a chunk, the server still enforces `X-Upload-Part-Number ≤ N`\nonce `N` has been learned from any prior chunk for the same upload that supplied `X-Upload-Total-Parts`.\n",
    ).optional(),
    xUploadTotalParts: z.int().describe(
      "Declared session total `N` (optional on chunks where omission is allowed). When present on a chunk,\nit must satisfy either `X-Upload-Part-Number < X-Upload-Total-Parts` (non-terminal) or\n`X-Upload-Part-Number == X-Upload-Total-Parts` (terminal). The same integer `N` must appear whenever\nthis header is sent for a given `X-Unique-Upload-Id` (no conflicting declared totals). Chunks may omit\nthe header entirely until `N` is established; after `N` is known, non-terminal indices may still omit\nit. Once `N` is known for the session, the request for part index `N` (the final part) must include\n`X-Upload-Total-Parts: N`. The upload completes when all parts `1`…`N` have been received.\n",
    ).optional(),
  });

/**
 * Chunk upload successful. For all but the final chunk, this returns upload status. For the final chunk, it returns the complete upload response.
 */
export type UploadChunkResponseBody =
  | AsyncUploadResponse
  | NonFinalChunkUploadResponse
  | UploadResponse;

export const UploadChunkResponseBody$zodSchema: z.ZodType<
  UploadChunkResponseBody
> = z.union([
  AsyncUploadResponse$zodSchema,
  NonFinalChunkUploadResponse$zodSchema,
  UploadResponse$zodSchema,
]).describe(
  "Chunk upload successful. For all but the final chunk, this returns upload status. For the final chunk, it returns the complete upload response.",
);

export type UploadChunkResponse =
  | ApiError
  | AsyncUploadResponse
  | NonFinalChunkUploadResponse
  | UploadResponse
  | string;

export const UploadChunkResponse$zodSchema: z.ZodType<UploadChunkResponse> = z
  .union([
    ApiError$zodSchema,
    z.union([
      AsyncUploadResponse$zodSchema,
      NonFinalChunkUploadResponse$zodSchema,
      UploadResponse$zodSchema,
    ]),
    z.string().describe(
      "Redirect to callback URL (when 'callback' parameter is provided and request is not XHR).",
    ),
  ]);
