/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af7a36564eab
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The delivery type for upload and rename operations. Includes the 'asset' type in addition to managed types.
 *
 * @remarks
 */
export const UploadDeliveryType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Asset: "asset",
} as const;
/**
 * The delivery type for upload and rename operations. Includes the 'asset' type in addition to managed types.
 *
 * @remarks
 */
export type UploadDeliveryType = ClosedEnum<typeof UploadDeliveryType>;

export const UploadDeliveryType$zodSchema = z.enum([
  "upload",
  "private",
  "authenticated",
  "asset",
]).describe(
  "The delivery type for upload and rename operations. Includes the 'asset' type in addition to managed types.\n",
);
