/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 52e17db37216
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  AsyncUploadResponse,
  AsyncUploadResponse$zodSchema,
} from "./asyncuploadresponse.js";
import {
  SchemeCloudinaryAuth,
  SchemeCloudinaryAuth$zodSchema,
} from "./schemecloudinaryauth.js";
import { UploadResponse, UploadResponse$zodSchema } from "./uploadresponse.js";

export const UploadNoResourceTypeOpServerList = [
  /**
   * Regional API endpoints for optimal performance.
   */
  "https://{region}.cloudinary.com",
  /**
   * Custom domains for enterprise deployments.
   */
  "https://{host}",
] as const;

export type UploadNoResourceTypeGlobals = { cloud_name?: string | undefined };

export const UploadNoResourceTypeGlobals$zodSchema: z.ZodType<
  UploadNoResourceTypeGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UploadNoResourceTypeSecurity = {
  cloudinaryAuth?: SchemeCloudinaryAuth | undefined;
  oauth2?: string | undefined;
};

export const UploadNoResourceTypeSecurity$zodSchema: z.ZodType<
  UploadNoResourceTypeSecurity
> = z.object({
  cloudinaryAuth: SchemeCloudinaryAuth$zodSchema.optional(),
  oauth2: z.string().describe(
    "OAuth2 Authorization Code flow for user authentication",
  ).optional(),
});

/**
 * Successful upload
 */
export type UploadNoResourceTypeResponseBody =
  | AsyncUploadResponse
  | UploadResponse;

export const UploadNoResourceTypeResponseBody$zodSchema: z.ZodType<
  UploadNoResourceTypeResponseBody
> = z.union([
  AsyncUploadResponse$zodSchema,
  UploadResponse$zodSchema,
]).describe("Successful upload");

export type UploadNoResourceTypeResponse =
  | ApiError
  | AsyncUploadResponse
  | UploadResponse
  | string;

export const UploadNoResourceTypeResponse$zodSchema: z.ZodType<
  UploadNoResourceTypeResponse
> = z.union([
  ApiError$zodSchema,
  z.union([
    AsyncUploadResponse$zodSchema,
    UploadResponse$zodSchema,
  ]),
  z.string().describe(
    "Redirect to callback URL (when 'callback' parameter is provided and request is not XHR).",
  ),
]);
