/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 764f09dd1b96
 */

import * as z from "zod";

export type VideoView = {
  video_public_id?: string | undefined;
  video_duration?: number | null | undefined;
  video_transformation?: string | null | undefined;
  video_extension?: string | null | undefined;
  viewer_application_name?: string | null | undefined;
  viewer_location_country_code?: string | null | undefined;
  viewer_os_identifier?: string | null | undefined;
  view_watch_time?: number | null | undefined;
  view_ended_at?: string | undefined;
};

export const VideoView$zodSchema: z.ZodType<VideoView> = z.object({
  video_duration: z.number().nullable().optional().describe(
    "The duration in seconds of the video.",
  ),
  video_extension: z.string().nullable().optional().describe(
    "The file extension of the video.",
  ),
  video_public_id: z.string().optional().describe(
    "The full public ID of the video.",
  ),
  video_transformation: z.string().nullable().optional().describe(
    "The transformation applied to the video.",
  ),
  view_ended_at: z.iso.datetime({ offset: true }).optional().describe(
    "The date when the video view ended.",
  ),
  view_watch_time: z.number().nullable().optional().describe(
    "The length of time the video was viewed.",
  ),
  viewer_application_name: z.string().nullable().optional().describe(
    "The application used to view the video.",
  ),
  viewer_location_country_code: z.string().nullable().optional().describe(
    "The 2-digit ISO country code of the viewer location.",
  ),
  viewer_os_identifier: z.string().nullable().optional().describe(
    "The full identifier for the viewer's operating system.",
  ),
});
