/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e6558f619e6
 */

import * as z from "zod";
import { VideoView, VideoView$zodSchema } from "./videoview.js";

export type VideoViewsResponse = {
  request_id?: string | undefined;
  next_cursor?: string | undefined;
  data?: Array<VideoView> | undefined;
};

export const VideoViewsResponse$zodSchema: z.ZodType<VideoViewsResponse> = z
  .object({
    data: z.array(VideoView$zodSchema).optional(),
    next_cursor: z.string().optional().describe("Cursor value for pagination."),
    request_id: z.string().optional().describe(
      "Unique identifier for the request.",
    ),
  });
